import { useState, type FormEvent } from 'react'
import { Navigate, NavLink, Route, Routes, useNavigate } from 'react-router'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { api, type Me } from './api'

function Shell({ me }: { me: Me }) {
  return <div className="app-shell"><aside><div className="brand"><span>R</span><div><strong>Ravencia</strong><small>Marketplace Hub</small></div></div><nav aria-label="Ana menü"><NavLink to="/dashboard">Genel Bakış</NavLink><NavLink to="/settings/security">Güvenlik</NavLink></nav><p className="scope">F1 Güvenli Temel</p></aside><main><header><div><small>Aktif oturum</small><strong>{me.displayName}</strong></div></header><Routes><Route path="/dashboard" element={<Dashboard me={me} />} /><Route path="/settings/security" element={<Security />} /><Route path="*" element={<Navigate to="/dashboard" replace />} /></Routes></main></div>
}

export function App() {
  const me = useQuery({ queryKey: ['me'], queryFn: () => api<Me>('/me'), retry: false })
  if (me.isLoading) return <Status title="Güvenli oturum doğrulanıyor" />
  if (me.isError) return <Routes><Route path="*" element={<Login />} /></Routes>
  if (!me.data) return <Status title="Oturum bilgisi alınamadı" />
  if (me.data.state === 'PASSWORD_CHANGE_REQUIRED') return <ChangePassword />
  if (me.data.state === 'MFA_CHALLENGE') return <MfaChallenge />
  if (me.data.state !== 'ACTIVE') return <Status title="Oturum kilitli" detail="Yeniden giriş yapın." />
  return <Shell me={me.data} />
}

function Login() {
  const navigate = useNavigate(); const client = useQueryClient(); const [error, setError] = useState('')
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); const data = new FormData(event.currentTarget); try { await api('/login', { method: 'POST', body: JSON.stringify({ email: data.get('email'), password: data.get('password') }) }); await client.invalidateQueries({ queryKey: ['me'] }); navigate('/dashboard') } catch (reason) { setError(reason instanceof Error ? reason.message : 'Giriş başarısız.') } }
  return <div className="auth-page"><section className="auth-card"><div className="brand large"><span>R</span><div><strong>Ravencia</strong><small>Marketplace Hub</small></div></div><p className="eyebrow">Güvenli yönetim paneli</p><h1>Tekrar hoş geldiniz</h1><p>Devam etmek için yönetici hesabınızla oturum açın.</p><form onSubmit={submit}><label>E-posta<input name="email" type="email" autoComplete="username" required /></label><label>Parola<input name="password" type="password" autoComplete="current-password" required minLength={15} maxLength={64} /></label>{error && <div role="alert" className="error">{error}</div>}<button type="submit">Güvenli giriş</button></form></section></div>
}

function ChangePassword() { const client = useQueryClient(); const [message, setMessage] = useState('İlk girişte parolanızı değiştirmeniz gerekir.'); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); try { await api('/change-password', { method: 'POST', body: JSON.stringify({ currentPassword: data.get('current'), newPassword: data.get('next') }) }); await client.invalidateQueries({ queryKey: ['me'] }) } catch { setMessage('Parola değiştirilemedi; politika ve mevcut parolayı kontrol edin.') } } return <div className="auth-page"><section className="auth-card"><h1>Parolanızı değiştirin</h1><p role="status">{message}</p><form onSubmit={submit}><label>Geçerli parola<input name="current" type="password" required /></label><label>Yeni parola<input name="next" type="password" minLength={15} maxLength={64} required /></label><button>Parolayı değiştir</button></form></section></div> }
function MfaChallenge() { const client = useQueryClient(); const [error, setError] = useState(''); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); try { await api('/mfa/challenge', { method: 'POST', body: JSON.stringify({ code: data.get('code'), recoveryCode: data.get('recovery') || null }) }); await client.invalidateQueries({ queryKey: ['me'] }) } catch { setError('Kod geçersiz veya daha önce kullanılmış.') } } return <div className="auth-page"><section className="auth-card"><h1>İki adımlı doğrulama</h1><p>Authenticator uygulamanızdaki 6 haneli kodu girin.</p><form onSubmit={submit}><label>Doğrulama kodu<input name="code" inputMode="numeric" pattern="[0-9]{6}" /></label><label>Kurtarma kodu (alternatif)<input name="recovery" /></label>{error && <div role="alert" className="error">{error}</div>}<button>Doğrula</button></form></section></div> }
function Dashboard({ me }: { me: Me }) { return <section className="content"><p className="eyebrow">Genel bakış</p><h1>Güvenli temel hazır</h1><p className="lede">Merhaba {me.displayName}. F1 kimlik, oturum, iş kuyruğu ve operasyon katmanı çalışır durumda.</p><div className="grid"><article><small>Oturum</small><strong>Aktif</strong><p>Sunucu tarafında doğrulandı</p></article><article><small>Tenant sınırı</small><strong>Etkin</strong><p>İş bağlamı sunucudan çözüldü</p></article><article><small>Dış yazma</small><strong>Kapalı</strong><p>Capability kanıtı bekleniyor</p></article></div></section> }
function Security() { const status = useQuery({ queryKey: ['security'], queryFn: () => api<{ totpState: string; recoveryCodesRemaining: number }>('/security-status') }); const sessions = useQuery({ queryKey: ['sessions'], queryFn: () => api<Array<{ id: string; state: string; current: boolean; lastSeenAt: string }>>('/sessions') }); return <section className="content"><p className="eyebrow">Ayarlar</p><h1>Güvenlik ve oturumlar</h1>{status.isLoading ? <Status title="Güvenlik durumu yükleniyor" /> : status.isError || !status.data ? <div role="alert" className="error">Güvenlik durumu alınamadı.</div> : <div className="panel"><h2>Authenticator</h2><p>Durum: <strong>{status.data.totpState}</strong></p><p>Kalan kurtarma kodu: <strong>{status.data.recoveryCodesRemaining}</strong></p></div>}<div className="panel"><h2>Oturumlar</h2>{sessions.isLoading ? <p>Yükleniyor…</p> : sessions.isError || !sessions.data ? <div role="alert" className="error">Oturumlar alınamadı.</div> : <ul className="sessions">{sessions.data.map(session => <li key={session.id}><span><strong>{session.current ? 'Bu cihaz' : 'Diğer oturum'}</strong><small>{session.state}</small></span><time>{new Date(session.lastSeenAt).toLocaleString('tr-TR')}</time></li>)}</ul>}</div></section> }
function Status({ title, detail }: { title: string; detail?: string }) { return <div className="status" role="status"><div className="spinner" /><strong>{title}</strong>{detail && <p>{detail}</p>}</div> }
