import { useState, type FormEvent } from 'react'
import { Link, Navigate, NavLink, Route, Routes, useLocation, useNavigate } from 'react-router'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { api, hubApi, type Me } from './api'
import { AttributesPage, BrandsPage, CategoriesPage, ImportDetailPage, ImportsPage, InventoryPage, NewProductPage, ProductDetailPage, ProductsPage } from './F2Pages'
import { IntegrationDetailPage, IntegrationsPage, MappingPage, OrderDetailPage, OrdersPage, ReturnDetailPage, ReturnsPage, ShipmentsPage } from './F3Pages'
import { BillingSettingsPage, InvoiceDetailPage, InvoicesPage } from './F4Pages'

function Shell({ me }: { me: Me }) {
  const location = useLocation(); const initials = me.displayName.split(' ').map(part => part[0]).join('').slice(0, 2).toLocaleUpperCase('tr-TR')
  const titles: Record<string, string> = { dashboard: 'Dashboard', products: 'Ürünler', catalog: 'Katalog', imports: 'İçe Aktarım', inventory: 'Stok', integrations: 'Platformlar · Trendyol · E-Faturam · Shopify · Hepsiburada', mappings: 'Eşleştirme Ayarları', orders: 'Siparişler', shipments: 'Gönderiler', returns: 'İadeler', invoices: 'Faturalar', settings: 'Ayarlar' }
  const current = titles[location.pathname.split('/')[1]] ?? 'Operasyon Merkezi'
  if (location.pathname === '/settings/billing') return <Navigate to="/dashboard" replace />
  const [settingsOpen, setSettingsOpen] = useState(location.pathname.startsWith('/settings') || location.pathname === '/integrations' || location.pathname.startsWith('/mappings'))
  const item = (to: string, icon: string, label: string) => <NavLink to={to}><span className="nav-icon" aria-hidden="true">{icon}</span>{label}</NavLink>
  return <div className="app-shell"><aside><div className="brand wordmark"><strong>RAVENCIA</strong><small>MERKEZ PANEL</small></div><nav aria-label="Ana menü"><span className="nav-section">Operasyon</span>{item('/dashboard', '▦', 'Dashboard')}{item('/products', '▣', 'Ürünler')}{item('/orders', '⌁', 'Siparişler')}{item('/returns', '↩', 'İadeler')}{item('/invoices', '▤', 'Faturalar')}</nav><div className="settings-nav"><button type="button" className="settings-toggle" aria-expanded={settingsOpen} onClick={() => setSettingsOpen(value => !value)}><span><span className="nav-icon" aria-hidden="true">⚙</span>Ayarlar</span><b aria-hidden="true">{settingsOpen ? '⌃' : '⌄'}</b></button>{settingsOpen && <div className="settings-links">{item('/integrations', '◎', 'Platformlar')}{item('/mappings/categories', '⇄', 'Eşleştirme Ayarları')}{item('/settings/security', '◌', 'Sistem Ayarları')}</div>}<Link className="logout-link" to="/settings/security"><span className="nav-icon" aria-hidden="true">↪</span>Çıkış Yap</Link></div></aside><main><header className="topbar"><div className="breadcrumb"><span>OPERASYON MERKEZİ</span><b>›</b><strong>{current.toLocaleUpperCase('tr-TR')}</strong></div><div className="top-actions"><span className="live-state"><i /> Sistem aktif</span><Link to="/integrations" className="sync-link">↯&nbsp; Senkronize et</Link><span className="avatar" title={me.displayName}>{initials}</span></div></header><Routes><Route path="/dashboard" element={<Dashboard me={me} />} /><Route path="/products" element={<ProductsPage />} /><Route path="/products/new" element={<NewProductPage />} /><Route path="/products/:id" element={<ProductDetailPage />} /><Route path="/catalog/categories" element={<CategoriesPage />} /><Route path="/catalog/brands" element={<BrandsPage />} /><Route path="/catalog/attributes" element={<AttributesPage />} /><Route path="/imports" element={<ImportsPage />} /><Route path="/imports/:id" element={<ImportDetailPage />} /><Route path="/inventory" element={<InventoryPage />} /><Route path="/integrations" element={<IntegrationsPage />} /><Route path="/integrations/:id" element={<IntegrationDetailPage />} /><Route path="/mappings/categories" element={<MappingPage kind="categories" />} /><Route path="/mappings/attributes" element={<MappingPage kind="attributes" />} /><Route path="/orders" element={<OrdersPage />} /><Route path="/orders/:id" element={<OrderDetailPage />} /><Route path="/shipments" element={<ShipmentsPage />} /><Route path="/returns" element={<ReturnsPage />} /><Route path="/returns/:id" element={<ReturnDetailPage />} /><Route path="/invoices" element={<InvoicesPage />} /><Route path="/invoices/:id" element={<InvoiceDetailPage />} /><Route path="/settings/billing" element={<BillingSettingsPage />} /><Route path="/settings/security" element={<Security />} /><Route path="*" element={<Navigate to="/dashboard" replace />} /></Routes></main></div>
}

export function App() {
  const me = useQuery({ queryKey: ['me'], queryFn: () => api<Me>('/me'), retry: false })
  if (me.isLoading) return <Status title="Güvenli oturum doğrulanıyor" />
  if (me.isError) return <Routes><Route path="*" element={<Login />} /></Routes>
  if (!me.data) return <Status title="Oturum bilgisi alınamadı" />
  if (me.data.state === 'PASSWORD_CHANGE_REQUIRED') return <ChangePassword />
  if (me.data.state === 'MFA_CHALLENGE') return <MfaChallenge />
  if (me.data.state !== 'ACTIVE') return <Status title="Oturum kilitli" detail="Yeniden giriş yapın." />
  return <Shell me={me.data} />
}

function Login() {
  const navigate = useNavigate(); const client = useQueryClient(); const [error, setError] = useState('')
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); const data = new FormData(event.currentTarget); try { await api('/login', { method: 'POST', body: JSON.stringify({ email: data.get('email'), password: data.get('password') }) }); await client.invalidateQueries({ queryKey: ['me'] }); navigate('/dashboard') } catch (reason) { setError(reason instanceof Error ? reason.message : 'Giriş başarısız.') } }
  return <div className="auth-page"><section className="auth-card"><div className="brand large"><span>R</span><div><strong>Ravencia</strong><small>Marketplace Hub</small></div></div><p className="eyebrow">Güvenli yönetim paneli</p><h1>Tekrar hoş geldiniz</h1><p>Devam etmek için yönetici hesabınızla oturum açın.</p><form onSubmit={submit}><label>E-posta<input name="email" type="email" autoComplete="username" required /></label><label>Parola<input name="password" type="password" autoComplete="current-password" required minLength={15} maxLength={64} /></label>{error && <div role="alert" className="error">{error}</div>}<button type="submit">Güvenli giriş</button></form></section></div>
}

function ChangePassword() { const client = useQueryClient(); const [message, setMessage] = useState('İlk girişte parolanızı değiştirmeniz gerekir.'); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); try { await api('/change-password', { method: 'POST', body: JSON.stringify({ currentPassword: data.get('current'), newPassword: data.get('next') }) }); await client.invalidateQueries({ queryKey: ['me'] }) } catch { setMessage('Parola değiştirilemedi; politika ve mevcut parolayı kontrol edin.') } } return <div className="auth-page"><section className="auth-card"><h1>Parolanızı değiştirin</h1><p role="status">{message}</p><form onSubmit={submit}><label>Geçerli parola<input name="current" type="password" required /></label><label>Yeni parola<input name="next" type="password" minLength={15} maxLength={64} required /></label><button>Parolayı değiştir</button></form></section></div> }
function MfaChallenge() { const client = useQueryClient(); const [error, setError] = useState(''); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); try { await api('/mfa/challenge', { method: 'POST', body: JSON.stringify({ code: data.get('code'), recoveryCode: data.get('recovery') || null }) }); await client.invalidateQueries({ queryKey: ['me'] }) } catch { setError('Kod geçersiz veya daha önce kullanılmış.') } } return <div className="auth-page"><section className="auth-card"><h1>İki adımlı doğrulama</h1><p>Authenticator uygulamanızdaki 6 haneli kodu girin.</p><form onSubmit={submit}><label>Doğrulama kodu<input name="code" inputMode="numeric" pattern="[0-9]{6}" /></label><label>Kurtarma kodu (alternatif)<input name="recovery" /></label>{error && <div role="alert" className="error">{error}</div>}<button>Doğrula</button></form></section></div> }
type DashboardPage<T> = { items: T[]; hasMore: boolean }
function Dashboard({ me }: { me: Me }) {
  const connections = useQuery({ queryKey: ['dashboard-connections'], queryFn: () => hubApi<DashboardPage<{ status: string }>>('/connections') })
  const orders = useQuery({ queryKey: ['dashboard-orders'], queryFn: () => hubApi<DashboardPage<{ derivedStatus: string }>>('/orders') })
  const invoices = useQuery({ queryKey: ['dashboard-invoices'], queryFn: () => hubApi<DashboardPage<{ status: string }>>('/invoices') })
  const loading = connections.isLoading || orders.isLoading || invoices.isLoading
  const verified = connections.data?.items.filter(item => item.status === 'VERIFIED' || item.status === 'ACTIVE').length ?? 0
  const openInvoices = invoices.data?.items.filter(item => !['COMPLETED', 'CANCELLED', 'CANCELLED_LOCAL'].includes(item.status)).length ?? 0
  return <section className="content dashboard"><div className="page-heading"><div><p className="eyebrow">Operasyon merkezi</p><h1>Genel Bakış</h1><p className="lede">Merhaba {me.displayName}. Pazaryeri operasyonlarınızın güncel ve güvenli özeti.</p></div><Link className="button-link" to="/integrations">↯ Senkronizasyon merkezi</Link></div>
    <div className="dashboard-toolbar"><div className="search-shell">⌕ <span>Sipariş, ürün veya bağlantı ara</span></div><Link className="button-link secondary" to="/orders">Siparişlere git</Link><Link className="button-link" to="/invoices">Faturaları yönet</Link></div>
    <div className="metrics dashboard-metrics"><article><small>BAĞLANTILAR</small><strong>{loading ? '—' : verified}</strong><p>Doğrulanmış veya aktif</p></article><article><small>SİPARİŞLER</small><strong>{loading ? '—' : orders.data?.items.length ?? 0}</strong><p>{orders.data?.hasMore ? 'İlk sayfadaki kayıtlar' : 'Görünen toplam kayıt'}</p></article><article><small>BEKLEYEN FATURA</small><strong>{loading ? '—' : openInvoices}</strong><p>İşlem veya inceleme bekliyor</p></article><article className="safe-metric"><small>DIŞ YAZMA</small><strong>Kapalı</strong><p>Güvenli çalışma modu</p></article></div>
    <div className="dashboard-panels"><article className="panel operation-card"><div className="panel-title"><div><h2>Operasyon Akışı</h2><p>Temel iş alanlarına hızlı erişim</p></div><span className="live-state"><i /> CANLI</span></div><div className="flow-grid"><Link to="/orders"><span>⌁</span><strong>Siparişler</strong><small>{orders.data?.items.length ?? 0} kayıt</small></Link><Link to="/shipments"><span>◇</span><strong>Gönderiler</strong><small>Paket takibi</small></Link><Link to="/invoices"><span>▤</span><strong>Faturalar</strong><small>{openInvoices} açık işlem</small></Link><Link to="/returns"><span>↩</span><strong>İadeler</strong><small>Talep yönetimi</small></Link></div></article><article className="panel safety-card"><p className="eyebrow">Güvenli çalışma</p><h2>Kontrollü entegrasyon modu</h2><p>Platform yazmaları; capability kanıtı, bağlantı anahtarı ve açık işlem onayı birlikte olmadan çalışmaz.</p><div className="safety-row"><span className="system-dot" /><div><strong>Production servisleri aktif</strong><small>Dış platform yazmaları kapalı</small></div></div><Link className="text-link" to="/settings/security">Güvenlik ayarlarını görüntüle →</Link></article></div>
  </section>
}
function Security() { const status = useQuery({ queryKey: ['security'], queryFn: () => api<{ totpState: string; recoveryCodesRemaining: number }>('/security-status') }); const sessions = useQuery({ queryKey: ['sessions'], queryFn: () => api<Array<{ id: string; state: string; current: boolean; lastSeenAt: string }>>('/sessions') }); return <section className="content"><p className="eyebrow">Ayarlar</p><h1>Güvenlik ve oturumlar</h1>{status.isLoading ? <Status title="Güvenlik durumu yükleniyor" /> : status.isError || !status.data ? <div role="alert" className="error">Güvenlik durumu alınamadı.</div> : <div className="panel"><h2>Authenticator</h2><p>Durum: <strong>{status.data.totpState}</strong></p><p>Kalan kurtarma kodu: <strong>{status.data.recoveryCodesRemaining}</strong></p></div>}<div className="panel"><h2>Oturumlar</h2>{sessions.isLoading ? <p>Yükleniyor…</p> : sessions.isError || !sessions.data ? <div role="alert" className="error">Oturumlar alınamadı.</div> : <ul className="sessions">{sessions.data.map(session => <li key={session.id}><span><strong>{session.current ? 'Bu cihaz' : 'Diğer oturum'}</strong><small>{session.state}</small></span><time>{new Date(session.lastSeenAt).toLocaleString('tr-TR')}</time></li>)}</ul>}</div></section> }
function Status({ title, detail }: { title: string; detail?: string }) { return <div className="status" role="status"><div className="spinner" /><strong>{title}</strong>{detail && <p>{detail}</p>}</div> }
