import { useState, type FormEvent } from 'react'
import { Link, useParams } from 'react-router'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { hubApi } from './api'

type Page<T> = { items: T[]; nextCursor: string | null; hasMore: boolean }
type Connection = { id: string; publicId: string; platformCode: string; environment: string; displayName: string; externalStoreId: string; status: string; apiVersion: string; lastTestedAt: string | null; lastSuccessAt: string | null; lastErrorCode: string | null; hasCredential: boolean; version: number }
type Capability = { code: string; supportLevel: string; sourceUrl: string | null; verifiedAt: string | null; constraintsJson: string | null }
type Order = { id: string; orderNumber: string; derivedStatus: string; currency: string; netAmount: number; orderedAt: string; lineCount: number; packageCount: number; version: number }
type OrderDetail = { id: string; orderNumber: string; derivedStatus: string; currency: string; grossAmount: number; discountAmount: number; netAmount: number; orderedAt: string; lines: Array<{ id: string; sku: string; barcode: string | null; title: string; orderedQuantity: number; cancelledQuantity: number; shippedQuantity: number; deliveredQuantity: number; returnedQuantity: number; unitPrice: number; rawStatus: string }>; packages: Shipment[]; version: number }
type Shipment = { id: string; orderId: string; orderNumber: string; externalPackageId: string; status: string; rawStatus: string; cargoTrackingNumber: string | null; statusOccurredAt: string; version: number }
type ReturnClaim = { id: string; externalClaimId: string; orderNumber: string; status: string; rawStatus: string; reasonText: string | null; actionDueAt: string | null; version: number }
type ReturnDetail = ReturnClaim & { reasonCode: string | null; allowedActions: string[] }

function idempotency() { return crypto.randomUUID() }
function ErrorBox({ error }: { error: unknown }) { return <div role="alert" className="error">{error instanceof Error ? error.message : 'İşlem tamamlanamadı.'}</div> }
function Busy({ text = 'Veriler yükleniyor…' }: { text?: string }) { return <div className="status inline" role="status"><div className="spinner" /><strong>{text}</strong></div> }
function Empty({ children }: { children: string }) { return <div className="empty"><strong>Kayıt yok</strong><p>{children}</p></div> }
function Badge({ value }: { value: string }) { const tone = value === 'SUPPORTED' || value === 'ACTIVE' || value === 'DELIVERED' || value === 'APPROVED' ? 'good' : value === 'UNKNOWN' || value === 'DRAFT' || value === 'VERIFIED' ? 'warn' : 'neutral'; return <span className={`badge ${tone}`}>{value}</span> }
function DateText({ value }: { value: string | null }) { return <>{value ? new Date(value).toLocaleString('tr-TR') : '—'}</> }

export function IntegrationsPage() {
  const client = useQueryClient(); const [error, setError] = useState(''); const query = useQuery({ queryKey: ['connections'], queryFn: () => hubApi<Page<Connection>>('/connections') })
  const create = useMutation({ mutationFn: (body: object) => hubApi<Connection>('/connections', { method: 'POST', headers: { 'Idempotency-Key': idempotency() }, body: JSON.stringify(body) }), onSuccess: () => client.invalidateQueries({ queryKey: ['connections'] }), onError: reason => setError(reason instanceof Error ? reason.message : 'Bağlantı oluşturulamadı.') })
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); const data = new FormData(event.currentTarget); create.mutate({ displayName: data.get('displayName'), environment: data.get('environment'), externalStoreId: data.get('externalStoreId'), apiVersion: 'V2', userAgentIdentity: data.get('userAgentIdentity') }) }
  return <section className="content f3"><div className="page-heading"><div><p className="eyebrow">Platform bağlantıları</p><h1>Trendyol V2</h1><p className="lede">Credential, environment ve capability kanıtı birbirinden ayrıdır. Dış yazmalar varsayılan olarak kapalıdır.</p></div><Badge value="F3" /></div>
    <div className="split"><div className="panel"><h2>Bağlantılar</h2>{query.isLoading ? <Busy /> : query.isError ? <ErrorBox error={query.error} /> : !query.data?.items.length ? <Empty>İlk Trendyol bağlantısını sağdaki güvenli formdan oluşturun.</Empty> : <div className="card-list">{query.data.items.map(item => <Link className="record-card" to={`/integrations/${item.id}`} key={item.id}><span><strong>{item.displayName}</strong><small>{item.environment} · mağaza {item.externalStoreId}</small></span><span><Badge value={item.status} /><small>{item.hasCredential ? 'Credential kayıtlı' : 'Credential bekleniyor'}</small></span></Link>)}</div>}</div>
      <form className="panel form-panel" onSubmit={submit}><h2>Yeni bağlantı</h2><label>Bağlantı adı<input name="displayName" required /></label><label>Environment<select name="environment" defaultValue="STAGE"><option>STAGE</option><option>PRODUCTION</option></select></label><label>Satıcı / mağaza kimliği<input name="externalStoreId" required /></label><label>User-Agent kimliği<input name="userAgentIdentity" placeholder="Firma-Adı - Entegrasyon-Adı" required /></label>{error && <div role="alert" className="error">{error}</div>}<button disabled={create.isPending}>{create.isPending ? 'Oluşturuluyor…' : 'Taslak bağlantı oluştur'}</button></form></div>
  </section>
}

export function IntegrationDetailPage() {
  const { id = '' } = useParams(); const client = useQueryClient(); const [notice, setNotice] = useState(''); const connection = useQuery({ queryKey: ['connection', id], queryFn: () => hubApi<Connection>(`/connections/${id}`) }); const capabilities = useQuery({ queryKey: ['capabilities', id], queryFn: () => hubApi<Capability[]>(`/connections/${id}/capabilities`) });
  const run = useMutation({ mutationFn: (request: { path: string; body?: object; version?: number }) => hubApi(request.path, { method: 'POST', headers: { 'Idempotency-Key': idempotency(), ...(request.version ? { 'If-Match': `"v${request.version}"` } : {}) }, body: JSON.stringify(request.body ?? {}) }), onSuccess: () => { setNotice('İş kuyruğa alındı.'); void client.invalidateQueries({ queryKey: ['connection', id] }) }, onError: reason => setNotice(reason instanceof Error ? reason.message : 'İşlem tamamlanamadı.') })
  async function credential(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!connection.data) return; const data = new FormData(event.currentTarget); try { await hubApi(`/connections/${id}/credential`, { method: 'PUT', headers: { 'Idempotency-Key': idempotency(), 'If-Match': `"v${connection.data.version}"` }, body: JSON.stringify({ apiKey: data.get('apiKey'), apiSecret: data.get('apiSecret') }) }); setNotice('Credential şifreli olarak yenilendi; değerler tekrar gösterilmeyecek.'); await client.invalidateQueries({ queryKey: ['connection', id] }) } catch (reason) { setNotice(reason instanceof Error ? reason.message : 'Credential kaydedilemedi.') } }
  if (connection.isLoading) return <section className="content"><Busy /></section>; if (connection.isError || !connection.data) return <section className="content"><ErrorBox error={connection.error} /></section>; const item = connection.data
  return <section className="content f3"><div className="page-heading"><div><Link to="/integrations" className="back">← Platformlar</Link><h1>{item.displayName}</h1><p className="lede">{item.environment} · mağaza {item.externalStoreId} · API {item.apiVersion}</p></div><Badge value={item.status} /></div>{notice && <div role="status" className="notice">{notice}</div>}
    <div className="grid"><article><small>Credential</small><strong>{item.hasCredential ? 'Şifreli kayıtlı' : 'Bekleniyor'}</strong><p>API key/secret hiçbir yanıtta gösterilmez.</p></article><article><small>Son test</small><strong><DateText value={item.lastTestedAt} /></strong><p>{item.lastErrorCode ?? 'Hata kaydı yok'}</p></article><article><small>Dış yazma</small><strong>Kapalı</strong><p>Stage safe-write kanıtı ve ayrı anahtar gerekir.</p></article></div>
    <div className="split"><form className="panel form-panel" onSubmit={credential}><h2>Credential döndür</h2><label>API key<input name="apiKey" type="password" autoComplete="off" required /></label><label>API secret<input name="apiSecret" type="password" autoComplete="new-password" required /></label><button>Şifreli kaydet</button><button type="button" className="secondary" disabled={!item.hasCredential || run.isPending} onClick={() => run.mutate({ path: `/connections/${id}/test-jobs` })}>Bağlantıyı test et</button></form>
      <div className="panel"><h2>Capability kanıtları</h2>{capabilities.isLoading ? <Busy /> : capabilities.isError ? <ErrorBox error={capabilities.error} /> : <div className="capability-list">{capabilities.data?.map(cap => <div key={cap.code}><span><strong>{cap.code}</strong><small><DateText value={cap.verifiedAt} /></small></span><Badge value={cap.supportLevel} /></div>)}</div>}</div></div>
  </section>
}

export function OrdersPage() { const query = useQuery({ queryKey: ['orders'], queryFn: () => hubApi<Page<Order>>('/orders') }); return <ListPage eyebrow="Satış" title="Siparişler" description="Webhook ve overlap’li cursor polling aynı dedupe hattında birleşir.">{query.isLoading ? <Busy /> : query.isError ? <ErrorBox error={query.error} /> : !query.data?.items.length ? <Empty>Aktif ve kanıtlanmış bir bağlantıdan order sync çalıştırıldığında siparişler burada görünür.</Empty> : <div className="data-table" role="table"><div className="table-head" role="row"><span>Sipariş</span><span>Durum</span><span>Tutar</span><span>Paket</span></div>{query.data.items.map(item => <Link role="row" to={`/orders/${item.id}`} key={item.id}><span><strong>{item.orderNumber}</strong><small><DateText value={item.orderedAt} /></small></span><Badge value={item.derivedStatus} /><span>{item.netAmount.toLocaleString('tr-TR', { style: 'currency', currency: item.currency })}</span><span>{item.packageCount}</span></Link>)}</div>}</ListPage> }

export function OrderDetailPage() { const { id = '' } = useParams(); const query = useQuery({ queryKey: ['order', id], queryFn: () => hubApi<OrderDetail>(`/orders/${id}`) }); if (query.isLoading) return <section className="content"><Busy /></section>; if (query.isError || !query.data) return <section className="content"><ErrorBox error={query.error} /></section>; const item = query.data; return <section className="content f3"><Link to="/orders" className="back">← Siparişler</Link><div className="page-heading"><div><p className="eyebrow">Sipariş detayı</p><h1>{item.orderNumber}</h1><p className="lede"><DateText value={item.orderedAt} /> · {item.netAmount.toLocaleString('tr-TR', { style: 'currency', currency: item.currency })}</p></div><Badge value={item.derivedStatus} /></div><div className="panel"><h2>Satırlar</h2><div className="data-table compact" role="table">{item.lines.map(line => <div role="row" key={line.id}><span><strong>{line.title}</strong><small>{line.sku}{line.barcode ? ` · ${line.barcode}` : ''}</small></span><span>{line.orderedQuantity} adet</span><span>{line.unitPrice.toLocaleString('tr-TR', { style: 'currency', currency: item.currency })}</span><Badge value={line.rawStatus || 'UNKNOWN'} /></div>)}</div></div><div className="panel"><h2>Paketler</h2>{!item.packages.length ? <Empty>Paket verisi henüz gelmedi.</Empty> : <div className="card-list">{item.packages.map(pack => <div className="record-card" key={pack.id}><span><strong>{pack.externalPackageId}</strong><small>{pack.cargoTrackingNumber ?? 'Takip numarası yok'}</small></span><Badge value={pack.status} /></div>)}</div>}</div></section> }

export function ShipmentsPage() { const query = useQuery({ queryKey: ['shipments'], queryFn: () => hubApi<Page<Shipment>>('/shipments') }); return <ListPage eyebrow="Operasyon" title="Gönderiler" description="Paket durumu geriye alınmaz; desteklenmeyen aksiyon ve etiket biçimleri gösterilmez.">{query.isLoading ? <Busy /> : query.isError ? <ErrorBox error={query.error} /> : !query.data?.items.length ? <Empty>Order ingestion sonrasında shipment package kayıtları burada görünür.</Empty> : <div className="data-table" role="table">{query.data.items.map(item => <div role="row" key={item.id}><span><strong>{item.orderNumber}</strong><small>Paket {item.externalPackageId}</small></span><Badge value={item.status} /><span>{item.cargoTrackingNumber ?? '—'}</span><span><DateText value={item.statusOccurredAt} /></span></div>)}</div>}</ListPage> }

export function ReturnsPage() { const query = useQuery({ queryKey: ['returns'], queryFn: () => hubApi<Page<ReturnClaim>>('/returns') }); return <ListPage eyebrow="Satış sonrası" title="İadeler" description="Karar, kanıt ve stok disposition kayıtları ayrı tutulur.">{query.isLoading ? <Busy /> : query.isError ? <ErrorBox error={query.error} /> : !query.data?.items.length ? <Empty>Kanıtlanmış return read sync sonrası iade talepleri burada görünür.</Empty> : <div className="data-table" role="table">{query.data.items.map(item => <Link role="row" to={`/returns/${item.id}`} key={item.id}><span><strong>{item.orderNumber}</strong><small>{item.externalClaimId}</small></span><Badge value={item.status} /><span>{item.reasonText ?? '—'}</span><span><DateText value={item.actionDueAt} /></span></Link>)}</div>}</ListPage> }

export function ReturnDetailPage() { const { id = '' } = useParams(); const query = useQuery({ queryKey: ['return', id], queryFn: () => hubApi<ReturnDetail>(`/returns/${id}`) }); if (query.isLoading) return <section className="content"><Busy /></section>; if (query.isError || !query.data) return <section className="content"><ErrorBox error={query.error} /></section>; const item = query.data; return <section className="content f3"><Link to="/returns" className="back">← İadeler</Link><div className="page-heading"><div><p className="eyebrow">İade detayı</p><h1>{item.orderNumber}</h1><p className="lede">Claim {item.externalClaimId}</p></div><Badge value={item.status} /></div><div className="split"><div className="panel"><h2>Talep</h2><dl className="details"><dt>Platform durumu</dt><dd>{item.rawStatus}</dd><dt>Neden</dt><dd>{item.reasonText ?? 'Belirtilmedi'}</dd><dt>Son aksiyon</dt><dd><DateText value={item.actionDueAt} /></dd></dl></div><div className="panel"><h2>Kullanılabilir aksiyonlar</h2>{item.allowedActions.length ? <div className="button-row">{item.allowedActions.map(action => <button key={action} disabled>{action}</button>)}</div> : <div className="unknown"><strong>Capability UNKNOWN</strong><p>Stage/SIT kanıtı olmadan dış iade aksiyonu sunulmaz.</p></div>}</div></div></section> }

export function MappingPage({ kind }: { kind: 'categories' | 'attributes' }) { return <ListPage eyebrow="Eşleştirme" title={kind === 'categories' ? 'Kategori eşlemeleri' : 'Özellik eşlemeleri'} description="Yayın öncesi yalnız güncel reference snapshot ve doğrulanmış eşlemeler kullanılır."><div className="unknown"><strong>Bağlantı seçimi gerekli</strong><p>Önce Trendyol bağlantısını test edin. Reference capability UNKNOWN iken canlı veri çağrısı veya varsayımsal eşleme yapılmaz.</p><Link className="button-link" to="/integrations">Platform bağlantılarına git</Link></div></ListPage> }

function ListPage({ eyebrow, title, description, children }: { eyebrow: string; title: string; description: string; children: React.ReactNode }) { return <section className="content f3"><div className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="lede">{description}</p></div><Badge value="LIVE READ" /></div><div className="panel">{children}</div></section> }
