import { useEffect, useState, type FormEvent } from 'react'
import { Link, useNavigate, useParams } from 'react-router'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { hubApi } from './api'

type Page<T> = { items: T[]; nextCursor: string | null; hasMore: boolean }
type Connection = { id: string; publicId: string; platformCode: string; environment: string; displayName: string; externalStoreId: string; status: string; apiVersion: string; lastTestedAt: string | null; lastSuccessAt: string | null; lastErrorCode: string | null; hasCredential: boolean; version: number }
type Capability = { code: string; supportLevel: string; sourceUrl: string | null; verifiedAt: string | null; constraintsJson: string | null }
type Order = { id: string; orderNumber: string; derivedStatus: string; currency: string; netAmount: number; orderedAt: string; lineCount: number; packageCount: number; version: number }
type OrderDetail = { id: string; orderNumber: string; derivedStatus: string; currency: string; grossAmount: number; discountAmount: number; netAmount: number; orderedAt: string; lines: Array<{ id: string; sku: string; barcode: string | null; title: string; orderedQuantity: number; cancelledQuantity: number; shippedQuantity: number; deliveredQuantity: number; returnedQuantity: number; unitPrice: number; vatRate: number; rawStatus: string }>; packages: Shipment[]; version: number }
type CreatedInvoice = { id: string }
type Shipment = { id: string; orderId: string; orderNumber: string; externalPackageId: string; status: string; rawStatus: string; cargoTrackingNumber: string | null; statusOccurredAt: string; version: number }
type ReturnClaim = { id: string; externalClaimId: string; orderNumber: string; status: string; rawStatus: string; reasonText: string | null; actionDueAt: string | null; version: number }
type ReturnDetail = ReturnClaim & { reasonCode: string | null; allowedActions: string[] }
type LocalCategory = { id: string; name: string; path: string; depth: number; isLeaf: boolean; isActive: boolean; version: number }
type ReferenceItem = { externalId: string; parentExternalId: string | null; name: string; path: string; depth: number; isLeaf: boolean; isActive: boolean }
type ReferenceData = { snapshotId: string; resourceType: string; fetchedAt: string; items: ReferenceItem[] }
type CatalogMapping = { id: string; connectionId: string; snapshotId: string; localId: string; externalId: string; status: string; verifiedAt: string | null; version: number }

function idempotency() { return crypto.randomUUID() }
function ErrorBox({ error }: { error: unknown }) { return <div role="alert" className="error">{error instanceof Error ? error.message : 'İşlem tamamlanamadı.'}</div> }
function Busy({ text = 'Veriler yükleniyor…' }: { text?: string }) { return <div className="status inline" role="status"><div className="spinner" /><strong>{text}</strong></div> }
function Empty({ children }: { children: string }) { return <div className="empty"><strong>Kayıt yok</strong><p>{children}</p></div> }
function Badge({ value }: { value: string }) { const tone = value === 'SUPPORTED' || value === 'ACTIVE' || value === 'DELIVERED' || value === 'APPROVED' ? 'good' : value === 'UNKNOWN' || value === 'DRAFT' || value === 'VERIFIED' ? 'warn' : 'neutral'; return <span className={`badge ${tone}`}>{value}</span> }
function DateText({ value }: { value: string | null }) { return <>{value ? new Date(value).toLocaleString('tr-TR') : '—'}</> }
const activePlatformCodes = new Set(['TRENDYOL', 'HEPSIBURADA', 'TRENDYOL_EFATURAM'])

export function IntegrationsPage() {
  const client = useQueryClient(); const [error, setError] = useState(''); const [platform, setPlatform] = useState('TRENDYOL'); const query = useQuery({ queryKey: ['connections'], queryFn: () => hubApi<Page<Connection>>('/connections') })
  const create = useMutation({ mutationFn: (body: object) => hubApi<Connection>('/connections', { method: 'POST', headers: { 'Idempotency-Key': idempotency() }, body: JSON.stringify(body) }), onSuccess: () => client.invalidateQueries({ queryKey: ['connections'] }), onError: reason => setError(reason instanceof Error ? reason.message : 'Bağlantı oluşturulamadı.') })
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); const data = new FormData(event.currentTarget); create.mutate({ displayName: data.get('displayName'), environment: data.get('environment'), externalStoreId: data.get('externalStoreId'), apiVersion: platform === 'TRENDYOL' ? 'V2' : platform === 'HEPSIBURADA' ? 'v1.0' : '1.0.0', userAgentIdentity: platform === 'TRENDYOL' || platform === 'HEPSIBURADA' ? data.get('userAgentIdentity') : null, platformCode: platform }) }
  const activeConnections = query.data?.items.filter(item => activePlatformCodes.has(item.platformCode)) ?? []
  return <section className="content f3"><div className="page-heading"><div><p className="eyebrow">Platform bağlantıları</p><h1>Trendyol, Hepsiburada ve Trendyol E-Faturam</h1><p className="lede">Aktif teslim kapsamı bu üç platformla sınırlıdır. Credential, ortam ve capability kanıtı birbirinden ayrıdır; dış yazmalar varsayılan olarak kapalıdır.</p></div><Badge value="ADR-015" /></div>
    {query.isLoading ? <Busy /> : query.isError ? <ErrorBox error={query.error} /> : <><div className="integration-grid">{activeConnections.map(item => <Link className="integration-card" to={`/integrations/${item.id}`} key={item.id}><div className="integration-card-top"><span className={`platform-mark ${item.platformCode.toLowerCase()}`}>{item.platformCode === 'TRENDYOL_EFATURAM' ? '▤' : '◉'}</span><span className={item.status === 'ACTIVE' || item.status === 'VERIFIED' ? 'connection-state connected' : 'connection-state'}><i />{item.status === 'ACTIVE' || item.status === 'VERIFIED' ? 'Bağlı' : 'Bağlı değil'}</span></div><h2>{item.displayName}</h2><p>{item.platformCode === 'TRENDYOL_EFATURAM' ? 'Fatura sağlayıcısı' : 'Sipariş kaynağı'}</p><div className="integration-details"><span>Ortam<strong>{item.environment}</strong></span><span>Mağaza kimliği<strong>{item.externalStoreId}</strong></span><span>Credential<strong>{item.hasCredential ? 'Şifreli kayıtlı' : 'Bekleniyor'}</strong></span></div><span className="connection-button">Bağlantıyı yönet →</span></Link>)}</div>{!activeConnections.length && <Empty>İlk aktif kapsam bağlantısını aşağıdaki güvenli formdan oluşturun.</Empty>}<form className="panel form-panel integration-create" onSubmit={submit}><h2>Yeni bağlantı</h2><div className="integration-form-grid"><label>Platform<select value={platform} onChange={event => setPlatform(event.target.value)}><option value="TRENDYOL">Trendyol V2</option><option value="HEPSIBURADA">Hepsiburada F6A</option><option value="TRENDYOL_EFATURAM">Trendyol E-Faturam</option></select></label><label>Bağlantı adı<input name="displayName" required /></label><label>Environment<select name="environment" defaultValue="STAGE"><option>STAGE</option><option>PRODUCTION</option></select></label><label>{platform === 'TRENDYOL' ? 'Satıcı / mağaza kimliği' : platform === 'HEPSIBURADA' ? 'Merchant kapsam kimliği' : 'Firma / partner kapsam kimliği'}<input name="externalStoreId" required /></label>{(platform === 'TRENDYOL' || platform === 'HEPSIBURADA') && <label>User-Agent kimliği<input name="userAgentIdentity" placeholder="Firma-Adı - Entegrasyon-Adı" required /></label>}</div>{error && <div role="alert" className="error">{error}</div>}<button disabled={create.isPending}>{create.isPending ? 'Oluşturuluyor…' : 'Taslak bağlantı oluştur'}</button></form></>}
  </section>
}

export function IntegrationDetailPage() {
  const { id = '' } = useParams(); const client = useQueryClient(); const [notice, setNotice] = useState(''); const connection = useQuery({ queryKey: ['connection', id], queryFn: () => hubApi<Connection>(`/connections/${id}`) }); const capabilities = useQuery({ queryKey: ['capabilities', id], queryFn: () => hubApi<Capability[]>(`/connections/${id}/capabilities`) });
  const run = useMutation({ mutationFn: (request: { path: string; body?: object; version?: number }) => hubApi(request.path, { method: 'POST', headers: { 'Idempotency-Key': idempotency(), ...(request.version ? { 'If-Match': `"v${request.version}"` } : {}) }, body: JSON.stringify(request.body ?? {}) }), onSuccess: () => { setNotice('İş kuyruğa alındı.'); void client.invalidateQueries({ queryKey: ['connection', id] }) }, onError: reason => setNotice(reason instanceof Error ? reason.message : 'İşlem tamamlanamadı.') })
  const activate = useMutation({ mutationFn: (version: number) => hubApi<Connection>(`/connections/${id}/active`, { method: 'PUT', headers: { 'Idempotency-Key': idempotency(), 'If-Match': `"v${version}"` }, body: JSON.stringify({ active: true }) }), onSuccess: () => { setNotice('Bağlantı etkinleştirildi.'); void client.invalidateQueries({ queryKey: ['connection', id] }); void client.invalidateQueries({ queryKey: ['connections'] }) }, onError: reason => setNotice(reason instanceof Error ? reason.message : 'Bağlantı etkinleştirilemedi.') })
  async function settings(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!connection.data) return; const data = new FormData(event.currentTarget); const efaturam = connection.data.platformCode === 'TRENDYOL_EFATURAM'; const body = { displayName: data.get('displayName'), userAgentIdentity: data.get('userAgentIdentity'), efaturamIntegrationModel: efaturam ? data.get('integrationModel') : null, efaturamCompanyId: efaturam ? Number(data.get('companyId')) : null, efaturamUserId: efaturam ? Number(data.get('userId')) : null, efaturamPrefix: efaturam ? data.get('prefix') : null, efaturamCarriers: [] }; try { await hubApi<Connection>(`/connections/${id}`, { method: 'PATCH', headers: { 'If-Match': `"v${connection.data.version}"` }, body: JSON.stringify(body) }); setNotice('Bağlantı ayarları güncellendi.'); await client.invalidateQueries({ queryKey: ['connection', id] }) } catch (reason) { setNotice(reason instanceof Error ? reason.message : 'Bağlantı ayarları güncellenemedi.') } }
  async function credential(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!connection.data) return; const data = new FormData(event.currentTarget); const body = connection.data.platformCode === 'TRENDYOL_EFATURAM' ? { email: data.get('email'), password: data.get('password') } : connection.data.platformCode === 'SHOPIFY' ? { accessToken: data.get('accessToken'), clientSecret: data.get('clientSecret') } : connection.data.platformCode === 'HEPSIBURADA' ? { username: data.get('username'), password: data.get('password') } : { apiKey: data.get('apiKey'), apiSecret: data.get('apiSecret') }; try { await hubApi(`/connections/${id}/credential`, { method: 'PUT', headers: { 'Idempotency-Key': idempotency(), 'If-Match': `"v${connection.data.version}"` }, body: JSON.stringify(body) }); setNotice('Credential şifreli olarak yenilendi; değerler tekrar gösterilmeyecek.'); await client.invalidateQueries({ queryKey: ['connection', id] }) } catch (reason) { setNotice(reason instanceof Error ? reason.message : 'Credential kaydedilemedi.') } }
  if (connection.isLoading) return <section className="content"><Busy /></section>; if (connection.isError || !connection.data) return <section className="content"><ErrorBox error={connection.error} /></section>; const item = connection.data
  if (!activePlatformCodes.has(item.platformCode)) return <section className="content f3"><Link to="/integrations" className="back">← Platformlar</Link><div className="unknown"><strong>Bağlantı aktif kapsam dışında</strong><p>ADR-015 uyarınca panel yalnız Trendyol, Hepsiburada ve Trendyol E-Faturam ile ilerler. Tarihsel bağlantı korunur fakat işlem sunulmaz.</p></div></section>
  const orderReadSupported = ((item.platformCode === 'TRENDYOL' && item.status === 'ACTIVE') || (item.platformCode === 'HEPSIBURADA' && item.status === 'VERIFIED')) && capabilities.data?.some(cap => cap.code === 'ORDER_READ' && cap.supportLevel === 'SUPPORTED') === true; const referenceReadSupported = item.platformCode === 'TRENDYOL' && item.status === 'ACTIVE' && capabilities.data?.some(cap => cap.code === 'REFERENCE_READ' && cap.supportLevel === 'SUPPORTED') === true
  return <section className="content f3"><div className="page-heading"><div><Link to="/integrations" className="back">← Platformlar</Link><h1>{item.displayName}</h1><p className="lede">{item.environment} · mağaza {item.externalStoreId} · API {item.apiVersion}</p></div><Badge value={item.status} /></div>{notice && <div role="status" className="notice">{notice}</div>}
    <div className="grid"><article><small>Credential</small><strong>{item.hasCredential ? 'Şifreli kayıtlı' : 'Bekleniyor'}</strong><p>API key/secret hiçbir yanıtta gösterilmez.</p></article><article><small>Son test</small><strong><DateText value={item.lastTestedAt} /></strong><p>{item.lastErrorCode ?? 'Hata kaydı yok'}</p></article><article><small>Dış yazma</small><strong>Kapalı</strong><p>Stage safe-write kanıtı ve ayrı anahtar gerekir.</p></article></div>
    {item.platformCode === 'TRENDYOL' && item.status === 'VERIFIED' && <div className="panel"><h2>Bağlantıyı etkinleştir</h2><p>Başarılı bağlantı testi kanıtı korunarak yalnız bu Trendyol bağlantısı etkinleştirilir. Dış yazmalar kapalı kalır.</p><button disabled={activate.isPending} onClick={() => activate.mutate(item.version)}>{activate.isPending ? 'Etkinleştiriliyor…' : 'Bağlantıyı ACTIVE yap'}</button></div>}
    {orderReadSupported && <div className="panel"><h2>Salt-okunur sipariş eşitleme</h2><p>Yalnız ORDER_READ=SUPPORTED kanıtı ile platform siparişleri okunur. Bu işlem dış platforma yazmaz.</p><button disabled={run.isPending} onClick={() => run.mutate({ path: `/connections/${id}/order-sync-jobs`, body: { externalOrderId: null } })}>{run.isPending ? 'Kuyruğa alınıyor…' : 'Siparişleri eşitle'}</button></div>}
    {referenceReadSupported && <div className="panel"><h2>Salt-okunur kategori eşitleme</h2><p>Yalnız REFERENCE_READ=SUPPORTED kanıtıyla Trendyol kategori ağacı okunup yerel snapshot olarak saklanır. Trendyol’a yazılmaz.</p><button disabled={run.isPending} onClick={() => run.mutate({ path: `/connections/${id}/reference-sync-jobs` })}>{run.isPending ? 'Kuyruğa alınıyor…' : 'Kategorileri eşitle'}</button></div>}
    {(item.platformCode === 'TRENDYOL' || item.platformCode === 'HEPSIBURADA') && <form className="panel form-panel" onSubmit={settings}><h2>Bağlantı ayarları</h2><label>Bağlantı adı<input name="displayName" defaultValue={item.displayName} required /></label><label>User-Agent kimliği<input name="userAgentIdentity" placeholder="Firma-Adı - Entegrasyon-Adı" autoComplete="off" required /></label><button>Bağlantı ayarlarını kaydet</button></form>}
    {item.platformCode === 'TRENDYOL_EFATURAM' && <form className="panel form-panel" onSubmit={settings}><h2>E-Faturam mali hesap ayarları</h2><p>İnternet satışı işaretlenmez; bu nedenle kargo bilgisi istenmez veya gönderilmez.</p><input name="displayName" type="hidden" value={item.displayName} /><label>Entegrasyon modeli<select name="integrationModel" defaultValue="API_USER"><option value="API_USER">Kendi firmam adına API kullanıcısı</option><option value="MARKETPLACE">Pazaryeri entegratörü</option></select></label><label>Company ID<input name="companyId" inputMode="numeric" min="1" required /></label><label>User ID<input name="userId" inputMode="numeric" min="1" required /></label><label>Fatura serisi (3 karakter)<input name="prefix" minLength={3} maxLength={3} pattern="[A-Za-z0-9]{3}" placeholder="RVN" /></label><button>Mali hesap ayarlarını kaydet</button><div className="unknown"><strong>Dış gönderim kapalı kalır</strong><p>Bu bilgiler kaydedilse bile test hesabı kanıtı ve capability onayı olmadan fatura gönderilmez.</p></div></form>}
    <div className="split"><form className="panel form-panel" onSubmit={credential}><h2>Credential döndür</h2>{item.platformCode === 'HEPSIBURADA' ? <><label>Merchant ID<input name="username" type="text" autoComplete="off" required /></label><label>Secret Key<input name="password" type="password" autoComplete="new-password" required /></label><div className="unknown"><strong>SIT salt-okunur sipariş kanıtı</strong><p>Dolu test siparişi doğrulanınca yalnız sipariş okuma açılır. Tüm dış yazmalar kapalıdır.</p></div></> : item.platformCode === 'TRENDYOL_EFATURAM' ? <><label>E-posta<input name="email" type="email" autoComplete="off" required /></label><label>Parola<input name="password" type="password" autoComplete="new-password" required /></label></> : <><label>API key<input name="apiKey" type="password" autoComplete="off" required /></label><label>API secret<input name="apiSecret" type="password" autoComplete="new-password" required /></label></>}<button disabled={run.isPending}>Şifreli kaydet</button><button type="button" className="secondary" disabled={!item.hasCredential || run.isPending} onClick={() => run.mutate({ path: `/connections/${id}/test-jobs` })}>Bağlantıyı test et</button></form>
      <div className="panel"><h2>Capability kanıtları</h2>{capabilities.isLoading ? <Busy /> : capabilities.isError ? <ErrorBox error={capabilities.error} /> : <div className="capability-list">{capabilities.data?.map(cap => <div key={cap.code}><span><strong>{cap.code}</strong><small><DateText value={cap.verifiedAt} /></small></span><Badge value={cap.supportLevel} /></div>)}</div>}</div></div>
  </section>
}

export function OrdersPage() {
  const [search, setSearch] = useState(''); const [status, setStatus] = useState('ALL')
  const query = useQuery({ queryKey: ['orders'], queryFn: () => hubApi<Page<Order>>('/orders') })
  const statuses = ['ALL', 'NEW', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED']
  const labels: Record<string, string> = { ALL: 'Tümü', NEW: 'Yeni', PROCESSING: 'Hazırlanıyor', SHIPPED: 'Kargoda', DELIVERED: 'Teslim Edildi', CANCELLED: 'İptal / İade' }
  const items = query.data?.items.filter(item => (status === 'ALL' || item.derivedStatus.toUpperCase() === status) && item.orderNumber.toLocaleLowerCase('tr-TR').includes(search.toLocaleLowerCase('tr-TR'))) ?? []
  return <section className="content f3 orders-page"><div className="page-heading"><div><p className="eyebrow">Sipariş yönetimi</p><h1>Siparişler</h1><p className="lede">Tüm satış kanallarındaki siparişleri tek ekrandan yönetin.</p></div><div className="page-heading-actions"><Badge value="LIVE READ" /><Link className="button-link" to="/integrations">+ Yeni bağlantı</Link></div></div>
    <div className="order-metrics metrics"><article><small>Toplam sipariş</small><strong>{query.data?.items.length ?? 0}</strong><span>tüm kanallar</span></article><article><small>Yeni siparişler</small><strong>{query.data?.items.filter(item => item.derivedStatus.toUpperCase() === 'NEW').length ?? 0}</strong><span>işlem bekliyor</span></article><article><small>Hazırlanıyor</small><strong>{query.data?.items.filter(item => item.derivedStatus.toUpperCase() === 'PROCESSING').length ?? 0}</strong><span>paketleme aşamasında</span></article><article><small>Toplam tutar</small><strong>{(query.data?.items.reduce((sum, item) => sum + item.netAmount, 0) ?? 0).toLocaleString('tr-TR', { style: 'currency', currency: query.data?.items[0]?.currency ?? 'TRY' })}</strong><span>KDV dahil</span></article></div>
    <div className="order-tabs" role="tablist" aria-label="Sipariş durumları">{statuses.map(value => <button type="button" role="tab" aria-selected={status === value} className={status === value ? 'active' : ''} key={value} onClick={() => setStatus(value)}>{labels[value]}</button>)}</div>
    <div className="order-toolbar"><label className="order-search"><span aria-hidden="true">⌕</span><input aria-label="Sipariş ara" value={search} onChange={event => setSearch(event.target.value)} placeholder="Sipariş numarası ara…" /></label><Link className="button-link secondary" to="/integrations">Platformlar</Link><Link className="button-link" to="/integrations">↯ Siparişleri eşitle</Link></div>
    {query.isLoading ? <Busy /> : query.isError ? <ErrorBox error={query.error} /> : !query.data?.items.length ? <Empty>Aktif ve kanıtlanmış bir bağlantıdan order sync çalıştırıldığında siparişler burada görünür.</Empty> : !items.length ? <Empty>Seçili filtreyle eşleşen sipariş bulunamadı.</Empty> : <div className="data-table orders-table" role="table"><div className="table-head" role="row"><span>Sipariş</span><span>Durum</span><span>Tutar</span><span>Paket</span></div>{items.map(item => <Link role="row" to={`/orders/${item.id}`} key={item.id}><span className="order-summary"><span className="order-thumb" aria-hidden="true">▧</span><span><strong>#{item.orderNumber}</strong><small><DateText value={item.orderedAt} /> · {item.lineCount} ürün</small></span></span><Badge value={item.derivedStatus} /><span><strong>{item.netAmount.toLocaleString('tr-TR', { style: 'currency', currency: item.currency })}</strong><small>KDV dahil</small></span><span><strong>{item.packageCount}</strong><small>paket</small></span></Link>)}</div>}
  </section>
}

export function OrderDetailPage() {
  const { id = '' } = useParams(); const navigate = useNavigate(); const [invoiceMessage, setInvoiceMessage] = useState('')
  const query = useQuery({ queryKey: ['order', id], queryFn: () => hubApi<OrderDetail>(`/orders/${id}`) })
  const connections = useQuery({ queryKey: ['connections'], queryFn: () => hubApi<Page<Connection>>('/connections') })
  const provider = connections.data?.items.find(x => x.platformCode === 'TRENDYOL_EFATURAM')
  const createInvoice = useMutation({ mutationFn: (packageId: string) => {
    if (!query.data || !provider) throw new Error('E-Faturam bağlantısı zorunludur.')
    return hubApi<CreatedInvoice>('/invoices', { method: 'POST', headers: { 'Idempotency-Key': `invoice:${query.data.id}:${packageId}` }, body: JSON.stringify({ orderId: query.data.id, packageId, providerConnectionId: provider.id, originalInvoiceId: null }) })
  }, onSuccess: invoice => navigate(`/invoices/${invoice.id}`), onError: error => setInvoiceMessage(error instanceof Error ? error.message : 'Fatura taslağı oluşturulamadı.') })
  if (query.isLoading) return <section className="content"><Busy /></section>; if (query.isError || !query.data) return <section className="content"><ErrorBox error={query.error} /></section>; const item = query.data
  const billingReady = !!provider && provider.hasCredential
  return <section className="content f3 order-detail-page"><Link to="/orders" className="back">← Siparişler</Link><div className="page-heading"><div><p className="eyebrow">Sipariş detayı</p><h1>{item.orderNumber}</h1><p className="lede"><DateText value={item.orderedAt} /> · {item.netAmount.toLocaleString('tr-TR', { style: 'currency', currency: item.currency })}</p></div><Badge value={item.derivedStatus} /></div>{invoiceMessage && <div role="alert" className="error">{invoiceMessage}</div>}<div className="panel order-lines-panel"><h2>Ürün detayları</h2><div className="data-table compact" role="table">{item.lines.map(line => <div role="row" key={line.id}><span className="order-line"><span className="order-thumb" aria-hidden="true">▧</span><span><strong>{line.title}</strong><small>{line.sku}{line.barcode ? ` · ${line.barcode}` : ''}</small></span></span><span>{line.orderedQuantity} adet</span><span>{line.unitPrice.toLocaleString('tr-TR', { style: 'currency', currency: item.currency })}</span><span>KDV %{line.vatRate}</span></div>)}</div></div><div className="panel order-package-panel"><h2>Paketler ve fatura</h2>{!item.packages.length ? <Empty>Paket verisi henüz gelmedi.</Empty> : <div className="card-list">{item.packages.map(pack => <div className="record-card" key={pack.id}><span><strong>{pack.externalPackageId}</strong><small>{pack.cargoTrackingNumber ?? 'Takip numarası yok'}</small></span><span><Badge value={pack.status} /><button disabled={!billingReady || createInvoice.isPending} onClick={() => createInvoice.mutate(pack.id)}>{createInvoice.isPending ? 'Hazırlanıyor…' : 'Fatura oluştur'}</button></span></div>)}</div>}{!billingReady && <div className="unknown"><strong>E-Faturam bağlantısı gerekli</strong><p>Şirket bilgileri E-Faturam hesabından kullanılır; yalnız şifreli bağlantı kaydı gerekir.</p><Link className="button-link" to="/integrations">E-Faturam bağlantısına git</Link></div>}</div></section>
}

export function ShipmentsPage() { const query = useQuery({ queryKey: ['shipments'], queryFn: () => hubApi<Page<Shipment>>('/shipments') }); return <ListPage eyebrow="Operasyon" title="Gönderiler" description="Paket durumu geriye alınmaz; desteklenmeyen aksiyon ve etiket biçimleri gösterilmez.">{query.isLoading ? <Busy /> : query.isError ? <ErrorBox error={query.error} /> : !query.data?.items.length ? <Empty>Order ingestion sonrasında shipment package kayıtları burada görünür.</Empty> : <div className="data-table" role="table">{query.data.items.map(item => <div role="row" key={item.id}><span><strong>{item.orderNumber}</strong><small>Paket {item.externalPackageId}</small></span><Badge value={item.status} /><span>{item.cargoTrackingNumber ?? '—'}</span><span><DateText value={item.statusOccurredAt} /></span></div>)}</div>}</ListPage> }

export function ReturnsPage() { const query = useQuery({ queryKey: ['returns'], queryFn: () => hubApi<Page<ReturnClaim>>('/returns') }); return <section className="content f3 returns-page"><div className="page-heading"><div><p className="eyebrow">Satış sonrası</p><h1>İade Yönetimi</h1><p className="lede">Müşteri iade taleplerini, inceleme süreçlerini ve onay durumlarını yönetin.</p></div><Badge value="LIVE READ" /></div><div className="return-tabs" role="tablist"><button type="button" className="active">Tüm İadeler <b>{query.data?.items.length ?? 0}</b></button><button type="button">Yeni Talepler</button><button type="button">İnceleme Bekliyor</button><button type="button">Onaylanan</button><button type="button">Reddedilen</button></div><div className="return-toolbar"><label className="order-search"><span aria-hidden="true">⌕</span><input aria-label="İade ara" placeholder="İade veya Sipariş No Ara..." /></label><button type="button" className="secondary">☷ Filtrele</button><button type="button" className="secondary">⇩ Dışa Aktar</button></div><div className="panel return-workspace">{query.isLoading ? <Busy /> : query.isError ? <ErrorBox error={query.error} /> : !query.data?.items.length ? <Empty>Kanıtlanmış return read sync sonrası iade talepleri burada görünür.</Empty> : <div className="data-table returns-table" role="table"><div className="table-head" role="row"><span>İade detayı</span><span>Müşteri & neden</span><span>Tarih / süre</span><span>Durum</span></div>{query.data.items.map(item => <Link role="row" to={`/returns/${item.id}`} key={item.id}><span className="return-summary"><span className="return-thumb" aria-hidden="true">↩</span><span><strong>{item.externalClaimId}</strong><small>Sipariş: {item.orderNumber}</small></span></span><span><strong>İade talebi</strong><small>{item.reasonText ?? 'Neden belirtilmedi'}</small></span><span><DateText value={item.actionDueAt} /></span><Badge value={item.status} /></Link>)}</div>}</div></section> }

export function ReturnDetailPage() { const { id = '' } = useParams(); const query = useQuery({ queryKey: ['return', id], queryFn: () => hubApi<ReturnDetail>(`/returns/${id}`) }); if (query.isLoading) return <section className="content"><Busy /></section>; if (query.isError || !query.data) return <section className="content"><ErrorBox error={query.error} /></section>; const item = query.data; return <section className="content f3"><Link to="/returns" className="back">← İadeler</Link><div className="page-heading"><div><p className="eyebrow">İade detayı</p><h1>{item.orderNumber}</h1><p className="lede">Claim {item.externalClaimId}</p></div><Badge value={item.status} /></div><div className="split"><div className="panel"><h2>Talep</h2><dl className="details"><dt>Platform durumu</dt><dd>{item.rawStatus}</dd><dt>Neden</dt><dd>{item.reasonText ?? 'Belirtilmedi'}</dd><dt>Son aksiyon</dt><dd><DateText value={item.actionDueAt} /></dd></dl></div><div className="panel"><h2>Kullanılabilir aksiyonlar</h2>{item.allowedActions.length ? <div className="button-row">{item.allowedActions.map(action => <button key={action} disabled>{action}</button>)}</div> : <div className="unknown"><strong>Capability UNKNOWN</strong><p>Stage/SIT kanıtı olmadan dış iade aksiyonu sunulmaz.</p></div>}</div></div></section> }

export function MappingPage({ kind }: { kind: 'categories' | 'attributes' }) {
  const client = useQueryClient(); const [connectionId, setConnectionId] = useState(''); const [localId, setLocalId] = useState(''); const [externalId, setExternalId] = useState(''); const [notice, setNotice] = useState('')
  const connections = useQuery({ queryKey: ['connections', 'mapping'], queryFn: () => hubApi<Page<Connection>>('/connections?limit=200') })
  const localCategories = useQuery({ queryKey: ['categories', 'mapping'], queryFn: () => hubApi<Page<LocalCategory>>('/catalog/categories?limit=200'), enabled: kind === 'categories' })
  const references = useQuery({ queryKey: ['reference-categories', connectionId], queryFn: () => hubApi<ReferenceData>(`/reference-data/categories?connectionId=${encodeURIComponent(connectionId)}`), enabled: kind === 'categories' && !!connectionId, retry: false })
  const mapping = useQuery({ queryKey: ['category-mapping', localId, connectionId], queryFn: () => hubApi<CatalogMapping | null>(`/mappings/categories/${localId}?connectionId=${encodeURIComponent(connectionId)}`), enabled: kind === 'categories' && !!localId && !!connectionId, retry: false })
  const save = useMutation({ mutationFn: () => {
    if (!references.data || !localId || !externalId) throw new Error('Bağlantı, panel kategorisi ve Trendyol kategorisi zorunludur.')
    return hubApi<CatalogMapping>(`/mappings/categories/${localId}`, { method: 'PUT', headers: mapping.data ? { 'If-Match': `"v${mapping.data.version}"` } : {}, body: JSON.stringify({ connectionId, snapshotId: references.data.snapshotId, externalId, status: 'VERIFIED' }) })
  }, onSuccess: async value => { setNotice('Kategori eşlemesi doğrulandı ve kaydedildi.'); setExternalId(value.externalId); await client.invalidateQueries({ queryKey: ['category-mapping', localId, connectionId] }) }, onError: reason => setNotice(reason instanceof Error ? reason.message : 'Eşleme kaydedilemedi.') })
  useEffect(() => { setExternalId(mapping.data?.externalId ?? '') }, [mapping.data])
  const trendyolConnections = connections.data?.items.filter(item => item.platformCode === 'TRENDYOL' && item.status === 'ACTIVE') ?? []
  const localLeaves = localCategories.data?.items.filter(item => item.isActive && item.isLeaf) ?? []
  const externalLeaves = references.data?.items.filter(item => item.isActive && item.isLeaf) ?? []

  if (kind === 'attributes') return <section className="content f3 mapping-page"><div className="page-heading"><div><p className="eyebrow">Eşleştirme ayarları</p><h1>Özellik eşlemeleri</h1><p className="lede">Özellik kaynağı henüz platform kanıtıyla doğrulanmadı.</p></div><Badge value="UNKNOWN" /></div><div className="unknown"><strong>Kanıtlanmış kaynak bekleniyor</strong><p>Yalnız kategori ağacı doğrulandı. Marka veya özellik endpoint’i varsayılmayacak ve dış platforma yazılmayacak.</p></div></section>

  return <section className="content f3 mapping-page"><div className="page-heading"><div><p className="eyebrow">Eşleştirme ayarları</p><h1>Kategori eşlemeleri</h1><p className="lede">Yerel yaprak kategoriyi doğrulanmış Trendyol kategori snapshot’ındaki bir yaprak kategoriyle eşleştirin.</p></div><Badge value="SAFE READ" /></div>{notice && <div role="status" className="notice">{notice}</div>}
    <article className="panel mapping-step"><div className="editor-section-title"><span>1</span><div><h2>Trendyol kategori eşlemesi</h2><p>Bu işlem yalnız yerel eşleme kaydı oluşturur; Trendyol’a veri göndermez.</p></div></div><div className="platform-choice"><strong>Pazaryeri:</strong><button type="button" className="active">Trendyol</button></div>
      <div className="mapping-fields"><label>Aktif Trendyol bağlantısı<select aria-label="Aktif Trendyol bağlantısı" value={connectionId} onChange={event => { setConnectionId(event.target.value); setLocalId(''); setExternalId(''); setNotice('') }}><option value="">Bağlantı seçin</option>{trendyolConnections.map(item => <option value={item.id} key={item.id}>{item.displayName} · {item.externalStoreId}</option>)}</select></label>
        <label>Panel yaprak kategorisi<select aria-label="Panel yaprak kategorisi" value={localId} onChange={event => { setLocalId(event.target.value); setExternalId(''); setNotice('') }} disabled={!connectionId}><option value="">Kategori seçin</option>{localLeaves.map(item => <option value={item.id} key={item.id}>{item.path}</option>)}</select></label>
        <label>Trendyol yaprak kategorisi<select aria-label="Trendyol yaprak kategorisi" value={externalId} onChange={event => setExternalId(event.target.value)} disabled={!localId || references.isLoading || references.isError}><option value="">Kategori seçin</option>{externalLeaves.map(item => <option value={item.externalId} key={item.externalId}>{item.path}</option>)}</select></label></div>
      {connections.isError || localCategories.isError ? <ErrorBox error={connections.error ?? localCategories.error} /> : !trendyolConnections.length && !connections.isLoading ? <div className="mapping-action"><span>REFERENCE_READ kanıtlı ACTIVE Trendyol bağlantısı gerekir.</span><Link className="button-link" to="/integrations">Platformlara git</Link></div> : references.isError ? <div className="unknown"><strong>Güncel kategori snapshot’ı yok</strong><p>Bağlantı ekranından “Kategorileri eşitle” işlemini çalıştırın.</p><Link className="button-link" to={`/integrations/${connectionId}`}>Bağlantıya git</Link></div> : references.isLoading ? <Busy text="Kategori snapshot’ı yükleniyor…" /> : connectionId && references.data ? <div className="mapping-action"><span>{externalLeaves.length.toLocaleString('tr-TR')} yaprak kategori · snapshot {new Date(references.data.fetchedAt).toLocaleString('tr-TR')}{mapping.data ? ` · mevcut eşleme v${mapping.data.version}` : ''}</span><button type="button" disabled={!localId || !externalId || save.isPending || mapping.isLoading} onClick={() => save.mutate()}>{save.isPending ? 'Kaydediliyor…' : mapping.data ? 'Eşlemeyi güncelle' : 'Eşlemeyi doğrula ve kaydet'}</button></div> : null}
    </article><article className="panel mapping-step"><div className="editor-section-title"><span>2</span><div><h2>Özellik eşlemeleri</h2><p>Kategori özelliği kaynağı ayrıca kanıtlanmadan açılmaz.</p></div></div><div className="unknown"><strong>Capability UNKNOWN</strong><p>Bu sürüm yalnız kanıtlanmış kategori ağacını kullanır; özellik veya marka verisi varsayılmaz.</p></div></article></section>
}

function ListPage({ eyebrow, title, description, children }: { eyebrow: string; title: string; description: string; children: React.ReactNode }) { return <section className="content f3"><div className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="lede">{description}</p></div><Badge value="LIVE READ" /></div><div className="panel">{children}</div></section> }
