import { useEffect, useState, type FormEvent } from 'react'
import { Link, useNavigate, useParams } from 'react-router'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { hubApi } from './api'

type Page<T> = { items: T[]; nextCursor: string | null; hasMore: boolean }
type Connection = { id: string; publicId: string; platformCode: string; environment: string; displayName: string; externalStoreId: string; status: string; apiVersion: string; lastTestedAt: string | null; lastSuccessAt: string | null; lastErrorCode: string | null; hasCredential: boolean; version: number }
type Capability = { code: string; supportLevel: string; sourceUrl: string | null; verifiedAt: string | null; constraintsJson: string | null; version: number }
type Order = { id: string; orderNumber: string; derivedStatus: string; currency: string; netAmount: number; orderedAt: string; lineCount: number; packageCount: number; version: number }
type OrderDetail = { id: string; orderNumber: string; derivedStatus: string; currency: string; grossAmount: number; discountAmount: number; netAmount: number; orderedAt: string; lines: Array<{ id: string; sku: string; barcode: string | null; title: string; orderedQuantity: number; cancelledQuantity: number; shippedQuantity: number; deliveredQuantity: number; returnedQuantity: number; unitPrice: number; vatRate: number; rawStatus: string }>; packages: Shipment[]; version: number }
type CreatedInvoice = { id: string }
type Shipment = { id: string; orderId: string; orderNumber: string; externalPackageId: string; status: string; rawStatus: string; cargoTrackingNumber: string | null; statusOccurredAt: string; version: number }
type ShipmentDetail = { package: Shipment; allowedActions: string[]; supportedLabelFormats: string[]; documents: Array<{ id: string; documentKind: string; format: string; source: string; documentVersion: number; createdAt: string; expiresAt: string | null }> }
type ReturnClaim = { id: string; externalClaimId: string; orderNumber: string; status: string; rawStatus: string; reasonText: string | null; actionDueAt: string | null; version: number }
type ReturnDetail = ReturnClaim & { reasonCode: string | null; allowedActions: string[] }
type LocalCategory = { id: string; name: string; path: string; depth: number; isLeaf: boolean; isActive: boolean; version: number }
type LocalBrand = { id: string; name: string; isActive: boolean; version: number }
type LocalAttribute = { id: string; code: string; name: string; dataType: string; isActive: boolean; version: number; values: { id: string; value: string; isActive: boolean }[] }
type ReferenceItem = { externalId: string; parentExternalId: string | null; name: string; path: string; depth: number; isLeaf: boolean; isActive: boolean; isRequired: boolean | null; allowsCustomValue: boolean | null; allowsMultipleValues: boolean | null }
type ReferenceData = { snapshotId: string; resourceType: string; fetchedAt: string; items: ReferenceItem[] }
type CatalogMapping = { id: string; connectionId: string; snapshotId: string; localId: string; scopeExternalId: string; externalId: string; status: string; verifiedAt: string | null; version: number }

function idempotency() { return crypto.randomUUID() }
function ErrorBox({ error }: { error: unknown }) { return <div role="alert" className="error">{error instanceof Error ? error.message : 'İşlem tamamlanamadı.'}</div> }
function Busy({ text = 'Veriler yükleniyor…' }: { text?: string }) { return <div className="status inline" role="status"><div className="spinner" /><strong>{text}</strong></div> }
function Empty({ children }: { children: string }) { return <div className="empty"><strong>Kayıt yok</strong><p>{children}</p></div> }
function Badge({ value }: { value: string }) { const tone = value === 'SUPPORTED' || value === 'ACTIVE' || value === 'DELIVERED' || value === 'APPROVED' ? 'good' : value === 'UNKNOWN' || value === 'DRAFT' || value === 'VERIFIED' ? 'warn' : 'neutral'; return <span className={`badge ${tone}`}>{value}</span> }
function DateText({ value }: { value: string | null }) { return <>{value ? new Date(value).toLocaleString('tr-TR') : '—'}</> }
const activePlatformCodes = new Set(['TRENDYOL', 'TRENDYOL_EFATURAM'])

export function IntegrationsPage() {
  const client = useQueryClient(); const [error, setError] = useState(''); const [platform, setPlatform] = useState('TRENDYOL'); const query = useQuery({ queryKey: ['connections'], queryFn: () => hubApi<Page<Connection>>('/connections') })
  const create = useMutation({ mutationFn: (body: object) => hubApi<Connection>('/connections', { method: 'POST', headers: { 'Idempotency-Key': idempotency() }, body: JSON.stringify(body) }), onSuccess: () => client.invalidateQueries({ queryKey: ['connections'] }), onError: reason => setError(reason instanceof Error ? reason.message : 'Bağlantı oluşturulamadı.') })
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); const data = new FormData(event.currentTarget); create.mutate({ displayName: data.get('displayName'), environment: data.get('environment'), externalStoreId: data.get('externalStoreId'), apiVersion: platform === 'TRENDYOL' ? 'V2' : '1.0.0', userAgentIdentity: platform === 'TRENDYOL' ? data.get('userAgentIdentity') : null, platformCode: platform }) }
  const activeConnections = query.data?.items.filter(item => activePlatformCodes.has(item.platformCode)) ?? []
  return <section className="content f3"><div className="page-heading"><div><p className="eyebrow">Platform bağlantıları</p><h1>Trendyol ve Trendyol E-Faturam</h1><p className="lede">Aktif teslim kapsamı bu iki entegrasyonla sınırlıdır. Credential, ortam ve capability kanıtı birbirinden ayrıdır; dış yazmalar varsayılan olarak kapalıdır.</p></div><Badge value="ADR-016" /></div>
    {query.isLoading ? <Busy /> : query.isError ? <ErrorBox error={query.error} /> : <><div className="integration-grid">{activeConnections.map(item => <Link className="integration-card" to={`/integrations/${item.id}`} key={item.id}><div className="integration-card-top"><span className={`platform-mark ${item.platformCode.toLowerCase()}`}>{item.platformCode === 'TRENDYOL_EFATURAM' ? '▤' : '◉'}</span><span className={item.status === 'ACTIVE' || item.status === 'VERIFIED' ? 'connection-state connected' : 'connection-state'}><i />{item.status === 'ACTIVE' || item.status === 'VERIFIED' ? 'Bağlı' : 'Bağlı değil'}</span></div><h2>{item.displayName}</h2><p>{item.platformCode === 'TRENDYOL_EFATURAM' ? 'Fatura sağlayıcısı' : 'Sipariş kaynağı'}</p><div className="integration-details"><span>Ortam<strong>{item.environment}</strong></span><span>{item.platformCode === 'TRENDYOL_EFATURAM' ? 'Yerel kapsam' : 'Mağaza kimliği'}<strong>{item.externalStoreId}</strong></span><span>Credential<strong>{item.hasCredential ? 'Şifreli kayıtlı' : 'Bekleniyor'}</strong></span></div><span className="connection-button">Bağlantıyı yönet →</span></Link>)}</div>{!activeConnections.length && <Empty>İlk aktif kapsam bağlantısını aşağıdaki güvenli formdan oluşturun.</Empty>}<form className="panel form-panel integration-create" onSubmit={submit}><h2>Yeni bağlantı</h2><div className="integration-form-grid"><label>Platform<select value={platform} onChange={event => setPlatform(event.target.value)}><option value="TRENDYOL">Trendyol V2</option><option value="TRENDYOL_EFATURAM">Trendyol E-Faturam</option></select></label><label>Bağlantı adı<input name="displayName" required /></label><label>Environment<select name="environment" defaultValue="STAGE"><option>STAGE</option><option>PRODUCTION</option></select></label><label>{platform === 'TRENDYOL' ? 'Satıcı / mağaza kimliği' : 'Yerel bağlantı kapsamı'}<input name="externalStoreId" placeholder={platform === 'TRENDYOL_EFATURAM' ? 'ravencia-efaturam' : undefined} required /></label>{platform === 'TRENDYOL' && <label>User-Agent kimliği<input name="userAgentIdentity" placeholder="Firma-Adı - Entegrasyon-Adı" required /></label>}</div>{error && <div role="alert" className="error">{error}</div>}<button disabled={create.isPending}>{create.isPending ? 'Oluşturuluyor…' : 'Taslak bağlantı oluştur'}</button></form></>}
  </section>
}

export function IntegrationDetailPage() {
  const { id = '' } = useParams(); const client = useQueryClient(); const [notice, setNotice] = useState(''); const connection = useQuery({ queryKey: ['connection', id], queryFn: () => hubApi<Connection>(`/connections/${id}`) }); const capabilities = useQuery({ queryKey: ['capabilities', id], queryFn: () => hubApi<Capability[]>(`/connections/${id}/capabilities`) });
  const run = useMutation({ mutationFn: (request: { path: string; body?: object; version?: number }) => hubApi(request.path, { method: 'POST', headers: { 'Idempotency-Key': idempotency(), ...(request.version ? { 'If-Match': `"v${request.version}"` } : {}) }, body: JSON.stringify(request.body ?? {}) }), onSuccess: () => { setNotice('İş kuyruğa alındı.'); void client.invalidateQueries({ queryKey: ['connection', id] }) }, onError: reason => setNotice(reason instanceof Error ? reason.message : 'İşlem tamamlanamadı.') })
  const activate = useMutation({ mutationFn: (version: number) => hubApi<Connection>(`/connections/${id}/active`, { method: 'PUT', headers: { 'Idempotency-Key': idempotency(), 'If-Match': `"v${version}"` }, body: JSON.stringify({ active: true }) }), onSuccess: () => { setNotice('Bağlantı etkinleştirildi.'); void client.invalidateQueries({ queryKey: ['connection', id] }); void client.invalidateQueries({ queryKey: ['connections'] }) }, onError: reason => setNotice(reason instanceof Error ? reason.message : 'Bağlantı etkinleştirilemedi.') })
  async function settings(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!connection.data) return; const data = new FormData(event.currentTarget); try { const body = { displayName: data.get('displayName'), userAgentIdentity: data.get('userAgentIdentity') }; await hubApi<Connection>(`/connections/${id}`, { method: 'PATCH', headers: { 'If-Match': `"v${connection.data.version}"` }, body: JSON.stringify(body) }); setNotice('Bağlantı ayarları güncellendi.'); await client.invalidateQueries({ queryKey: ['connection', id] }) } catch (reason) { setNotice(reason instanceof Error ? reason.message : 'Bağlantı ayarları güncellenemedi.') } }
  async function credential(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!connection.data) return; const data = new FormData(event.currentTarget); const body = connection.data.platformCode === 'TRENDYOL_EFATURAM' ? { email: data.get('email') || null, password: data.get('password') || null } : { apiKey: data.get('apiKey'), apiSecret: data.get('apiSecret') }; try { await hubApi(`/connections/${id}/credential`, { method: 'PUT', headers: { 'Idempotency-Key': idempotency(), 'If-Match': `"v${connection.data.version}"` }, body: JSON.stringify(body) }); setNotice('Credential şifreli olarak yenilendi; değerler tekrar gösterilmeyecek.'); await client.invalidateQueries({ queryKey: ['connection', id] }) } catch (reason) { setNotice(reason instanceof Error ? reason.message : 'Credential kaydedilemedi.') } }
  async function evidence(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const code = String(data.get('code') || ''); const capability = capabilities.data?.find(value => value.code === code); if (!capability) return; try { const constraints = String(data.get('constraintsJson') || '').trim(); await hubApi(`/connections/${id}/capabilities/${encodeURIComponent(code)}/evidence`, { method: 'PUT', headers: { 'Idempotency-Key': idempotency(), 'If-Match': `\"v${capability.version}\"` }, body: JSON.stringify({ supportLevel: data.get('supportLevel'), sourceUrl: data.get('sourceUrl'), sourceVersion: data.get('sourceVersion'), environment: item.environment, storeScope: item.externalStoreId, evidenceNote: data.get('evidenceNote'), fixtureChecksum: data.get('fixtureChecksum') || null, constraintsJson: constraints || null, verifiedAt: new Date(String(data.get('verifiedAt'))).toISOString() }) }); setNotice('Capability kanıtı audit kaydıyla güncellendi.'); await client.invalidateQueries({ queryKey: ['capabilities', id] }) } catch (reason) { setNotice(reason instanceof Error ? reason.message : 'Capability kanıtı kaydedilemedi.') } }
  if (connection.isLoading) return <section className="content"><Busy /></section>; if (connection.isError || !connection.data) return <section className="content"><ErrorBox error={connection.error} /></section>; const item = connection.data
  if (!activePlatformCodes.has(item.platformCode)) return <section className="content f3"><Link to="/integrations" className="back">← Platformlar</Link><div className="unknown"><strong>Bağlantı aktif kapsam dışında</strong><p>ADR-016 uyarınca panel yalnız Trendyol ve Trendyol E-Faturam ile ilerler. Kapsam dışı tarihsel bağlantılara işlem sunulmaz.</p></div></section>
  const orderReadSupported = item.platformCode === 'TRENDYOL' && item.status === 'ACTIVE' && capabilities.data?.some(cap => cap.code === 'ORDER_READ' && cap.supportLevel === 'SUPPORTED') === true; const referenceReadSupported = item.platformCode === 'TRENDYOL' && item.status === 'ACTIVE' && capabilities.data?.some(cap => cap.code === 'REFERENCE_READ' && cap.supportLevel === 'SUPPORTED') === true
  return <section className="content f3"><div className="page-heading"><div><Link to="/integrations" className="back">← Platformlar</Link><h1>{item.displayName}</h1><p className="lede">{item.environment} · {item.platformCode === 'TRENDYOL_EFATURAM' ? 'yerel kapsam' : 'mağaza'} {item.externalStoreId} · API {item.apiVersion}</p></div><Badge value={item.status} /></div>{notice && <div role="status" className="notice">{notice}</div>}
    <div className="grid"><article><small>Credential</small><strong>{item.hasCredential ? 'Şifreli kayıtlı' : 'Bekleniyor'}</strong><p>API key/secret hiçbir yanıtta gösterilmez.</p></article><article><small>Son test</small><strong><DateText value={item.lastTestedAt} /></strong><p>{item.lastErrorCode ?? 'Hata kaydı yok'}</p></article><article><small>Dış yazma</small><strong>Kapalı</strong><p>Stage safe-write kanıtı ve ayrı anahtar gerekir.</p></article></div>
    {item.platformCode === 'TRENDYOL' && item.status === 'VERIFIED' && <div className="panel"><h2>Bağlantıyı etkinleştir</h2><p>Başarılı bağlantı testi kanıtı korunarak yalnız bu Trendyol bağlantısı etkinleştirilir. Dış yazmalar kapalı kalır.</p><button disabled={activate.isPending} onClick={() => activate.mutate(item.version)}>{activate.isPending ? 'Etkinleştiriliyor…' : 'Bağlantıyı ACTIVE yap'}</button></div>}
    {orderReadSupported && <div className="panel"><h2>Salt-okunur sipariş eşitleme</h2><p>Yalnız ORDER_READ=SUPPORTED kanıtı ile platform siparişleri okunur. Bu işlem dış platforma yazmaz.</p><button disabled={run.isPending} onClick={() => run.mutate({ path: `/connections/${id}/order-sync-jobs`, body: { externalOrderId: null } })}>{run.isPending ? 'Kuyruğa alınıyor…' : 'Siparişleri eşitle'}</button></div>}
    {referenceReadSupported && <div className="panel"><h2>Salt-okunur katalog referansları</h2><p>Yalnız REFERENCE_READ=SUPPORTED kanıtıyla kategori ve marka listeleri yerel snapshot olarak saklanır. Trendyol’a yazılmaz.</p><div className="button-row"><button disabled={run.isPending} onClick={() => run.mutate({ path: `/connections/${id}/reference-sync-jobs?resourceType=CATEGORIES` })}>{run.isPending ? 'Kuyruğa alınıyor…' : 'Kategorileri eşitle'}</button><button className="secondary" disabled={run.isPending} onClick={() => run.mutate({ path: `/connections/${id}/reference-sync-jobs?resourceType=BRANDS` })}>{run.isPending ? 'Kuyruğa alınıyor…' : 'Markaları eşitle'}</button><Link className="button-link secondary" to="/mappings/categories?view=brands">Marka eşlemelerine git</Link></div></div>}
    {item.platformCode === 'TRENDYOL' && <form className="panel form-panel" onSubmit={settings}><h2>Bağlantı ayarları</h2><label>Bağlantı adı<input name="displayName" defaultValue={item.displayName} required /></label><label>User-Agent kimliği<input name="userAgentIdentity" placeholder="Firma-Adı - Entegrasyon-Adı" autoComplete="off" required /></label><button>Bağlantı ayarlarını kaydet</button></form>}
    {item.platformCode === 'TRENDYOL_EFATURAM' && <article className="panel"><h2>E-Faturam hesabı otomatik yönetilir</h2><p>Firma kimliği, kullanıcı kimliği ve varsayılan fatura serisi panelden girilmez. E-posta/parola ile açılan E-Faturam oturumundaki firma kapsamı ve varsayılan seri kullanılır.</p><div className="card-list"><div className="record-card"><span><strong>Belge türü</strong><small>Kurumsal ve E-Fatura mükellefi: TEMELFATURA; diğer siparişler: EARSIVFATURA</small></span><Badge value="AUTO" /></div><div className="record-card"><span><strong>İnternet satışı ek alanları</strong><small>Kullanıcı ayarı değildir; gerekli olduğunda Trendyol siparişi ve resmî kargo kataloğundan otomatik hazırlanır.</small></span><Badge value="AUTO" /></div></div></article>}
    <div className="split"><form className="panel form-panel" onSubmit={credential}><h2>Credential döndür</h2>{item.platformCode === 'TRENDYOL_EFATURAM' ? <><label>E-Faturam e-postası<input name="email" type="email" autoComplete="username" required /></label><label>E-Faturam parolası<input name="password" type="password" autoComplete="new-password" required /></label><p>Firma ve kullanıcı kimlikleri giriş tokenından alınır; mali hesap bilgisi panelde saklanmaz veya tekrar gösterilmez.</p></> : <><label>API key<input name="apiKey" type="password" autoComplete="off" required /></label><label>API secret<input name="apiSecret" type="password" autoComplete="new-password" required /></label></>}<button disabled={run.isPending}>Şifreli kaydet</button><button type="button" className="secondary" disabled={!item.hasCredential || run.isPending} onClick={() => run.mutate({ path: `/connections/${id}/test-jobs` })}>Bağlantıyı test et</button></form>
      <div className="panel"><h2>Capability kanıtları</h2>{capabilities.isLoading ? <Busy /> : capabilities.isError ? <ErrorBox error={capabilities.error} /> : <div className="capability-list">{capabilities.data?.map(cap => <div key={cap.code}><span><strong>{cap.code}</strong><small><DateText value={cap.verifiedAt} /></small></span><Badge value={cap.supportLevel} /></div>)}</div>}</div></div>
    {capabilities.data?.length ? <form className="panel form-panel" onSubmit={evidence}><h2>Stage/SIT capability kanıtı kaydet</h2><p>Yalnız Owner/Administrator kullanabilir. Write capability SUPPORTED için Stage/SIT fixture SHA-256 zorunludur.</p><label>Capability<select name="code">{capabilities.data.map(cap => <option key={cap.code}>{cap.code}</option>)}</select></label><label>Destek seviyesi<select name="supportLevel" defaultValue="UNKNOWN"><option>UNKNOWN</option><option>SUPPORTED</option><option>NOT_SUPPORTED</option></select></label><label>Resmî kaynak URL<input name="sourceUrl" type="url" placeholder="https://developers.trendyol.com veya developers.trendyolefaturam.com/..." required /></label><label>Kaynak sürümü<input name="sourceVersion" defaultValue="V2" required /></label><label>Doğrulama zamanı<input name="verifiedAt" type="datetime-local" required /></label><label>Kanıt notu<textarea name="evidenceNote" maxLength={1000} required /></label><label>Stage/SIT fixture SHA-256<input name="fixtureChecksum" minLength={64} maxLength={64} /></label><label>Kısıtlar JSON<textarea name="constraintsJson" placeholder='{"allowedActions":["PICKING","TRACKING_NUMBER"]}' /></label><button>Kanıtı kaydet</button></form> : null}
  </section>
}

export function OrdersPage() {
  const [search, setSearch] = useState(''); const [status, setStatus] = useState('ALL')
  const query = useQuery({ queryKey: ['orders'], queryFn: () => hubApi<Page<Order>>('/orders') })
  const statuses = ['ALL', 'NEW', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED']
  const labels: Record<string, string> = { ALL: 'Tümü', NEW: 'Yeni', PROCESSING: 'Hazırlanıyor', SHIPPED: 'Kargoda', DELIVERED: 'Teslim Edildi', CANCELLED: 'İptal / İade' }
  const items = query.data?.items.filter(item => (status === 'ALL' || item.derivedStatus.toUpperCase() === status) && item.orderNumber.toLocaleLowerCase('tr-TR').includes(search.toLocaleLowerCase('tr-TR'))) ?? []
  return <section className="content f3 orders-page"><div className="page-heading"><div><p className="eyebrow">Sipariş yönetimi</p><h1>Siparişler</h1><p className="lede">Tüm satış kanallarındaki siparişleri tek ekrandan yönetin.</p></div><div className="page-heading-actions"><Badge value="LIVE READ" /><Link className="button-link" to="/integrations">+ Yeni bağlantı</Link></div></div>
    <div className="order-metrics metrics"><article><small>Toplam sipariş</small><strong>{query.data?.items.length ?? 0}</strong><span>tüm kanallar</span></article><article><small>Yeni siparişler</small><strong>{query.data?.items.filter(item => item.derivedStatus.toUpperCase() === 'NEW').length ?? 0}</strong><span>işlem bekliyor</span></article><article><small>Hazırlanıyor</small><strong>{query.data?.items.filter(item => item.derivedStatus.toUpperCase() === 'PROCESSING').length ?? 0}</strong><span>paketleme aşamasında</span></article><article><small>Toplam tutar</small><strong>{(query.data?.items.reduce((sum, item) => sum + item.netAmount, 0) ?? 0).toLocaleString('tr-TR', { style: 'currency', currency: query.data?.items[0]?.currency ?? 'TRY' })}</strong><span>KDV dahil</span></article></div>
    <div className="order-tabs" role="tablist" aria-label="Sipariş durumları">{statuses.map(value => <button type="button" role="tab" aria-selected={status === value} className={status === value ? 'active' : ''} key={value} onClick={() => setStatus(value)}>{labels[value]}</button>)}</div>
    <div className="order-toolbar"><label className="order-search"><span aria-hidden="true">⌕</span><input aria-label="Sipariş ara" value={search} onChange={event => setSearch(event.target.value)} placeholder="Sipariş numarası ara…" /></label><Link className="button-link secondary" to="/integrations">Platformlar</Link><Link className="button-link" to="/integrations">↯ Siparişleri eşitle</Link></div>
    {query.isLoading ? <Busy /> : query.isError ? <ErrorBox error={query.error} /> : !query.data?.items.length ? <Empty>Aktif ve kanıtlanmış bir bağlantıdan order sync çalıştırıldığında siparişler burada görünür.</Empty> : !items.length ? <Empty>Seçili filtreyle eşleşen sipariş bulunamadı.</Empty> : <div className="data-table orders-table" role="table"><div className="table-head" role="row"><span>Sipariş</span><span>Durum</span><span>Tutar</span><span>Paket</span></div>{items.map(item => <Link role="row" to={`/orders/${item.id}`} key={item.id}><span className="order-summary"><span className="order-thumb" aria-hidden="true">▧</span><span><strong>#{item.orderNumber}</strong><small><DateText value={item.orderedAt} /> · {item.lineCount} ürün</small></span></span><Badge value={item.derivedStatus} /><span><strong>{item.netAmount.toLocaleString('tr-TR', { style: 'currency', currency: item.currency })}</strong><small>KDV dahil</small></span><span><strong>{item.packageCount}</strong><small>paket</small></span></Link>)}</div>}
  </section>
}

export function OrderDetailPage() {
  const { id = '' } = useParams(); const navigate = useNavigate(); const [invoiceMessage, setInvoiceMessage] = useState('')
  const query = useQuery({ queryKey: ['order', id], queryFn: () => hubApi<OrderDetail>(`/orders/${id}`) })
  const connections = useQuery({ queryKey: ['connections'], queryFn: () => hubApi<Page<Connection>>('/connections') })
  const provider = connections.data?.items.find(x => x.platformCode === 'TRENDYOL_EFATURAM')
  const createInvoice = useMutation({ mutationFn: (packageId: string) => {
    if (!query.data || !provider) throw new Error('E-Faturam bağlantısı zorunludur.')
    return hubApi<CreatedInvoice>('/invoices', { method: 'POST', headers: { 'Idempotency-Key': `invoice:${query.data.id}:${packageId}` }, body: JSON.stringify({ orderId: query.data.id, packageId, providerConnectionId: provider.id, originalInvoiceId: null }) })
  }, onSuccess: invoice => navigate(`/invoices/${invoice.id}`), onError: error => setInvoiceMessage(error instanceof Error ? error.message : 'Fatura taslağı oluşturulamadı.') })
  if (query.isLoading) return <section className="content"><Busy /></section>; if (query.isError || !query.data) return <section className="content"><ErrorBox error={query.error} /></section>; const item = query.data
  const billingReady = !!provider && provider.hasCredential
  return <section className="content f3 order-detail-page"><Link to="/orders" className="back">← Siparişler</Link><div className="page-heading"><div><p className="eyebrow">Sipariş detayı</p><h1>{item.orderNumber}</h1><p className="lede"><DateText value={item.orderedAt} /> · {item.netAmount.toLocaleString('tr-TR', { style: 'currency', currency: item.currency })}</p></div><Badge value={item.derivedStatus} /></div>{invoiceMessage && <div role="alert" className="error">{invoiceMessage}</div>}<div className="panel order-lines-panel"><h2>Ürün detayları</h2><div className="data-table compact" role="table">{item.lines.map(line => <div role="row" key={line.id}><span className="order-line"><span className="order-thumb" aria-hidden="true">▧</span><span><strong>{line.title}</strong><small>{line.sku}{line.barcode ? ` · ${line.barcode}` : ''}</small></span></span><span>{line.orderedQuantity} adet</span><span>{line.unitPrice.toLocaleString('tr-TR', { style: 'currency', currency: item.currency })}</span><span>KDV %{line.vatRate}</span></div>)}</div></div><div className="panel order-package-panel"><h2>Paketler ve fatura</h2>{!item.packages.length ? <Empty>Paket verisi henüz gelmedi.</Empty> : <div className="card-list">{item.packages.map(pack => <div className="record-card" key={pack.id}><span><strong>{pack.externalPackageId}</strong><small>{pack.cargoTrackingNumber ?? 'Takip numarası yok'}</small></span><span><Badge value={pack.status} /><button disabled={!billingReady || createInvoice.isPending} onClick={() => createInvoice.mutate(pack.id)}>{createInvoice.isPending ? 'Hazırlanıyor…' : 'Fatura oluştur'}</button></span></div>)}</div>}{!billingReady && <div className="unknown"><strong>E-Faturam bağlantısı gerekli</strong><p>Şirket bilgileri E-Faturam hesabından kullanılır; yalnız şifreli bağlantı kaydı gerekir.</p><Link className="button-link" to="/integrations">E-Faturam bağlantısına git</Link></div>}</div></section>
}

export function ShipmentsPage() { const query = useQuery({ queryKey: ['shipments'], queryFn: () => hubApi<Page<Shipment>>('/shipments') }); return <ListPage eyebrow="Operasyon" title="Gönderiler" description="Paket durumu geriye alınmaz; desteklenmeyen aksiyon ve etiket biçimleri gösterilmez.">{query.isLoading ? <Busy /> : query.isError ? <ErrorBox error={query.error} /> : !query.data?.items.length ? <Empty>Order ingestion sonrasında shipment package kayıtları burada görünür.</Empty> : <div className="data-table" role="table">{query.data.items.map(item => <Link role="row" to={`/shipments/${item.id}`} key={item.id}><span><strong>{item.orderNumber}</strong><small>Paket {item.externalPackageId}</small></span><Badge value={item.status} /><span>{item.cargoTrackingNumber ?? '—'}</span><span><DateText value={item.statusOccurredAt} /></span></Link>)}</div>}</ListPage> }

export function ShipmentDetailPage() {
  const { id = '' } = useParams(); const client = useQueryClient(); const [notice, setNotice] = useState(''); const query = useQuery({ queryKey: ['shipment', id], queryFn: () => hubApi<ShipmentDetail>(`/shipments/${id}`) })
  async function action(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!query.data) return; const data = new FormData(event.currentTarget); try { JSON.parse(String(data.get('payloadJson') || '{}')); await hubApi(`/shipments/${id}/actions`, { method: 'POST', headers: { 'Idempotency-Key': idempotency(), 'If-Match': `"v${query.data.package.version}"` }, body: JSON.stringify({ action: data.get('action'), payloadJson: data.get('payloadJson') }) }); setNotice('Paket aksiyonu kuyruğa alındı; sonuç read-back ile doğrulanacak.'); await client.invalidateQueries({ queryKey: ['shipment', id] }) } catch (reason) { setNotice(reason instanceof Error ? reason.message : 'Aksiyon başlatılamadı.') } }
  async function label(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!query.data) return; const data = new FormData(event.currentTarget); try { await hubApi(`/shipments/${id}/common-label-jobs`, { method: 'POST', headers: { 'Idempotency-Key': idempotency(), 'If-Match': `"v${query.data.package.version}"` }, body: JSON.stringify({ boxQuantity: Number(data.get('boxQuantity')), volumetricHeight: Number(data.get('volumetricHeight')) }) }); setNotice('Ortak etiket işi kuyruğa alındı.'); await client.invalidateQueries({ queryKey: ['shipment', id] }) } catch (reason) { setNotice(reason instanceof Error ? reason.message : 'Etiket işi başlatılamadı.') } }
  if (query.isLoading) return <section className="content"><Busy /></section>; if (query.isError || !query.data) return <section className="content"><ErrorBox error={query.error} /></section>; const item = query.data
  return <section className="content f3"><Link to="/shipments" className="back">← Gönderiler</Link><div className="page-heading"><div><p className="eyebrow">Gönderi detayı</p><h1>{item.package.orderNumber}</h1><p className="lede">Paket {item.package.externalPackageId}</p></div><Badge value={item.package.status} /></div>{notice && <div role="status" className="notice">{notice}</div>}<div className="split"><article className="panel"><h2>Paket</h2><dl className="details"><dt>Platform durumu</dt><dd>{item.package.rawStatus}</dd><dt>Takip numarası</dt><dd>{item.package.cargoTrackingNumber ?? '—'}</dd><dt>Güncelleme</dt><dd><DateText value={item.package.statusOccurredAt} /></dd></dl><h3>Belgeler</h3>{item.documents.length ? <ul className="plain-list">{item.documents.map(document => <li key={document.id}><strong>{document.documentKind} · {document.format}</strong><span>v{document.documentVersion} · {document.source}</span></li>)}</ul> : <p>Henüz belge yok.</p>}</article><article className="panel"><h2>Trendyol paket aksiyonu</h2>{item.allowedActions.length ? <form className="form-grid" onSubmit={action}><label>Aksiyon<select name="action">{item.allowedActions.map(value => <option key={value}>{value}</option>)}</select></label><label>Resmî aksiyon payload JSON<textarea name="payloadJson" defaultValue="{}" required /></label><button>Aksiyonu kuyruğa al</button></form> : <div className="unknown"><strong>Shipment write kapalı</strong><p>Stage/SIT capability kanıtı olmadan dış aksiyon gösterilmez.</p></div>}<h2>Ortak kargo etiketi</h2>{item.supportedLabelFormats.length && item.package.cargoTrackingNumber ? <form className="inline-form" onSubmit={label}><label>Koli adedi<input name="boxQuantity" type="number" min="1" max="50" defaultValue="1" required /></label><label>Desi / hacim<input name="volumetricHeight" type="number" min="0" max="10000" step="0.01" defaultValue="1" required /></label><button>Etiket oluştur</button></form> : <p className="notice">Etiket capability'si veya takip numarası yok.</p>}</article></div></section>
}

export function ReturnsPage() {
  const [status, setStatus] = useState('ALL')
  const [search, setSearch] = useState('')
  const query = useQuery({ queryKey: ['returns'], queryFn: () => hubApi<Page<ReturnClaim>>('/returns') })
  const items = query.data?.items ?? []
  const normalized = search.trim().toLocaleLowerCase('tr-TR')
  const visible = items.filter(item => (status === 'ALL' || item.status === status) && (!normalized || [item.externalClaimId, item.orderNumber, item.reasonText ?? ''].some(value => value.toLocaleLowerCase('tr-TR').includes(normalized))))
  const tabs = [['ALL', 'Tüm İadeler'], ['NEW', 'Yeni Talepler'], ['UNDER_REVIEW', 'İnceleme Bekliyor'], ['APPROVED', 'Onaylanan'], ['REJECTED', 'Reddedilen']] as const
  return <section className="content f3 returns-page"><div className="page-heading"><div><p className="eyebrow">Satış sonrası</p><h1>İade Yönetimi</h1><p className="lede">Müşteri iade taleplerini, inceleme süreçlerini ve onay durumlarını yönetin.</p></div><Badge value="LIVE READ" /></div><div className="return-tabs" role="tablist">{tabs.map(([value, label]) => <button key={value} type="button" role="tab" aria-selected={status === value} className={status === value ? 'active' : ''} onClick={() => setStatus(value)}>{label} {value === 'ALL' && <b>{items.length}</b>}</button>)}</div><div className="return-toolbar"><label className="order-search"><span aria-hidden="true">⌕</span><input aria-label="İade ara" placeholder="İade veya Sipariş No Ara..." value={search} onChange={event => setSearch(event.target.value)} /></label><button type="button" className="secondary" disabled title="Gelişmiş filtreler planlanmıştır.">☷ Filtrele · Planlandı</button><button type="button" className="secondary" disabled title="Dışa aktarma güvenli CSV fazında açılacaktır.">⇩ Dışa Aktar · Planlandı</button></div><div className="panel return-workspace">{query.isLoading ? <Busy /> : query.isError ? <ErrorBox error={query.error} /> : !visible.length ? <Empty>{items.length ? 'Seçili filtreyle eşleşen iade yok.' : 'Kanıtlanmış return read sync sonrası iade talepleri burada görünür.'}</Empty> : <div className="data-table returns-table" role="table"><div className="table-head" role="row"><span>İade detayı</span><span>Müşteri & neden</span><span>Tarih / süre</span><span>Durum</span></div>{visible.map(item => <Link role="row" to={`/returns/${item.id}`} key={item.id}><span className="return-summary"><span className="return-thumb" aria-hidden="true">↩</span><span><strong>{item.externalClaimId}</strong><small>Sipariş: {item.orderNumber}</small></span></span><span><strong>İade talebi</strong><small>{item.reasonText ?? 'Neden belirtilmedi'}</small></span><span><DateText value={item.actionDueAt} /></span><Badge value={item.status} /></Link>)}</div>}</div></section>
}


export function ReturnDetailPage() {
  const { id = '' } = useParams(); const client = useQueryClient(); const [notice, setNotice] = useState(''); const [evidenceAssetIds, setEvidenceAssetIds] = useState<string[]>([]); const query = useQuery({ queryKey: ['return', id], queryFn: () => hubApi<ReturnDetail>(`/returns/${id}`) })
  async function upload(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const file = data.get('file'); if (!(file instanceof File) || !file.size) return; const body = new FormData(); body.set('file', file); try { const asset = await hubApi<{ id: string }>('/files/return-evidence', { method: 'POST', body }); setEvidenceAssetIds(ids => ids.includes(asset.id) ? ids : [...ids, asset.id]); setNotice('Kanıt güvenli özel depoya yüklendi.') } catch (reason) { setNotice(reason instanceof Error ? reason.message : 'Kanıt yüklenemedi.') } }
  async function decide(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!query.data) return; const data = new FormData(event.currentTarget); const action = String(data.get('action') || '').toUpperCase(); try { await hubApi(`/returns/${id}/actions`, { method: 'POST', headers: { 'Idempotency-Key': idempotency(), 'If-Match': `"v${query.data.version}"` }, body: JSON.stringify({ action, reasonCode: action === 'REJECT' ? data.get('reasonCode') : null, explanation: action === 'REJECT' ? data.get('explanation') : null, evidenceAssetIds }) }); setNotice('İade kararı kuyruğa alındı; uzak read-back sonucu bekleniyor.'); await client.invalidateQueries({ queryKey: ['return', id] }) } catch (reason) { setNotice(reason instanceof Error ? reason.message : 'İade kararı başlatılamadı.') } }
  if (query.isLoading) return <section className="content"><Busy /></section>; if (query.isError || !query.data) return <section className="content"><ErrorBox error={query.error} /></section>; const item = query.data
  return <section className="content f3"><Link to="/returns" className="back">← İadeler</Link><div className="page-heading"><div><p className="eyebrow">İade detayı</p><h1>{item.orderNumber}</h1><p className="lede">Claim {item.externalClaimId}</p></div><Badge value={item.status} /></div>{notice && <div role="status" className="notice">{notice}</div>}<div className="split"><div className="panel"><h2>Talep</h2><dl className="details"><dt>Platform durumu</dt><dd>{item.rawStatus}</dd><dt>Neden</dt><dd>{item.reasonText ?? 'Belirtilmedi'}</dd><dt>Son aksiyon</dt><dd><DateText value={item.actionDueAt} /></dd></dl><form onSubmit={upload}><label>Ret kanıtı (PDF/JPEG/PNG, en fazla 10 MiB)<input name="file" type="file" accept="application/pdf,image/jpeg,image/png" /></label><button className="secondary">Kanıt yükle</button><small>{evidenceAssetIds.length} kanıt hazır</small></form></div><div className="panel"><h2>Kullanılabilir aksiyonlar</h2>{item.allowedActions.length ? <form className="form-grid" onSubmit={decide}><label>Karar<select name="action">{item.allowedActions.filter(value => value === 'APPROVE' || value === 'REJECT').map(action => <option key={action}>{action}</option>)}</select></label><label>Ret neden kodu<input name="reasonCode" /></label><label>Ret açıklaması<textarea name="explanation" maxLength={500} /></label><button>Kararı kuyruğa al</button></form> : <div className="unknown"><strong>Capability UNKNOWN</strong><p>Stage/SIT kanıtı olmadan dış iade aksiyonu sunulmaz.</p></div>}</div></div></section>
}

export function MappingPage({ kind }: { kind: 'categories' | 'attributes' }) {
  const client = useQueryClient(); const [connectionId, setConnectionId] = useState(''); const [localId, setLocalId] = useState(''); const [externalId, setExternalId] = useState(''); const [notice, setNotice] = useState('')
  const connections = useQuery({ queryKey: ['connections', 'mapping'], queryFn: () => hubApi<Page<Connection>>('/connections?limit=200') })
  const localCategories = useQuery({ queryKey: ['categories', 'mapping'], queryFn: () => hubApi<Page<LocalCategory>>('/catalog/categories?limit=200'), enabled: kind === 'categories' })
  const references = useQuery({ queryKey: ['reference-categories', connectionId], queryFn: () => hubApi<ReferenceData>(`/reference-data/categories?connectionId=${encodeURIComponent(connectionId)}`), enabled: kind === 'categories' && !!connectionId, retry: false })
  const mapping = useQuery({ queryKey: ['category-mapping', localId, connectionId], queryFn: () => hubApi<CatalogMapping | null>(`/mappings/categories/${localId}?connectionId=${encodeURIComponent(connectionId)}`), enabled: kind === 'categories' && !!localId && !!connectionId, retry: false })
  const save = useMutation({ mutationFn: () => {
    if (!references.data || !localId || !externalId) throw new Error('Bağlantı, panel kategorisi ve Trendyol kategorisi zorunludur.')
    return hubApi<CatalogMapping>(`/mappings/categories/${localId}`, { method: 'PUT', headers: mapping.data ? { 'If-Match': `"v${mapping.data.version}"` } : {}, body: JSON.stringify({ connectionId, snapshotId: references.data.snapshotId, externalId, status: 'VERIFIED' }) })
  }, onSuccess: async value => { setNotice('Kategori eşlemesi doğrulandı ve kaydedildi.'); setExternalId(value.externalId); await client.invalidateQueries({ queryKey: ['category-mapping', localId, connectionId] }) }, onError: reason => setNotice(reason instanceof Error ? reason.message : 'Eşleme kaydedilemedi.') })
  useEffect(() => { setExternalId(mapping.data?.externalId ?? '') }, [mapping.data])
  const trendyolConnections = connections.data?.items.filter(item => item.platformCode === 'TRENDYOL' && item.status === 'ACTIVE') ?? []
  const localLeaves = localCategories.data?.items.filter(item => item.isActive && item.isLeaf) ?? []
  const externalLeaves = references.data?.items.filter(item => item.isActive && item.isLeaf) ?? []

  if (kind === 'categories' && new URLSearchParams(window.location.search).get('view') === 'brands') return <BrandMappingPage />
  if (kind === 'attributes') return <AttributeMappingPage />

  return <section className="content f3 mapping-page"><div className="page-heading"><div><p className="eyebrow">Eşleştirme ayarları</p><h1>Kategori eşlemeleri</h1><p className="lede">Yerel yaprak kategoriyi doğrulanmış Trendyol kategori snapshot’ındaki bir yaprak kategoriyle eşleştirin.</p></div><Badge value="SAFE READ" /></div>{notice && <div role="status" className="notice">{notice}</div>}
    <article className="panel mapping-step"><div className="editor-section-title"><span>1</span><div><h2>Trendyol kategori eşlemesi</h2><p>Bu işlem yalnız yerel eşleme kaydı oluşturur; Trendyol’a veri göndermez.</p></div></div><div className="platform-choice"><strong>Pazaryeri:</strong><button type="button" className="active">Trendyol</button></div>
      <div className="mapping-fields"><label>Aktif Trendyol bağlantısı<select aria-label="Aktif Trendyol bağlantısı" value={connectionId} onChange={event => { setConnectionId(event.target.value); setLocalId(''); setExternalId(''); setNotice('') }}><option value="">Bağlantı seçin</option>{trendyolConnections.map(item => <option value={item.id} key={item.id}>{item.displayName} · {item.externalStoreId}</option>)}</select></label>
        <label>Panel yaprak kategorisi<select aria-label="Panel yaprak kategorisi" value={localId} onChange={event => { setLocalId(event.target.value); setExternalId(''); setNotice('') }} disabled={!connectionId}><option value="">Kategori seçin</option>{localLeaves.map(item => <option value={item.id} key={item.id}>{item.path}</option>)}</select></label>
        <label>Trendyol yaprak kategorisi<select aria-label="Trendyol yaprak kategorisi" value={externalId} onChange={event => setExternalId(event.target.value)} disabled={!localId || references.isLoading || references.isError}><option value="">Kategori seçin</option>{externalLeaves.map(item => <option value={item.externalId} key={item.externalId}>{item.path}</option>)}</select></label></div>
      {connections.isError || localCategories.isError ? <ErrorBox error={connections.error ?? localCategories.error} /> : !trendyolConnections.length && !connections.isLoading ? <div className="mapping-action"><span>REFERENCE_READ kanıtlı ACTIVE Trendyol bağlantısı gerekir.</span><Link className="button-link" to="/integrations">Platformlara git</Link></div> : references.isError ? <div className="unknown"><strong>Güncel kategori snapshot’ı yok</strong><p>Bağlantı ekranından “Kategorileri eşitle” işlemini çalıştırın.</p><Link className="button-link" to={`/integrations/${connectionId}`}>Bağlantıya git</Link></div> : references.isLoading ? <Busy text="Kategori snapshot’ı yükleniyor…" /> : connectionId && references.data ? <div className="mapping-action"><span>{externalLeaves.length.toLocaleString('tr-TR')} yaprak kategori · snapshot {new Date(references.data.fetchedAt).toLocaleString('tr-TR')}{mapping.data ? ` · mevcut eşleme v${mapping.data.version}` : ''}</span><button type="button" disabled={!localId || !externalId || save.isPending || mapping.isLoading} onClick={() => save.mutate()}>{save.isPending ? 'Kaydediliyor…' : mapping.data ? 'Eşlemeyi güncelle' : 'Eşlemeyi doğrula ve kaydet'}</button></div> : null}
    </article><article className="panel mapping-step"><div className="editor-section-title"><span>2</span><div><h2>Özellik eşlemeleri</h2><p>Kategori özelliği kaynağı ayrıca kanıtlanmadan açılmaz.</p></div></div><div className="unknown"><strong>Capability UNKNOWN</strong><p>Bu sürüm yalnız kanıtlanmış kategori ağacını kullanır; özellik veya marka verisi varsayılmaz.</p></div></article></section>
}

export function AttributeMappingPage() {
  const client = useQueryClient(); const [connectionId, setConnectionId] = useState(''); const [categoryId, setCategoryId] = useState(''); const [localId, setLocalId] = useState(''); const [externalId, setExternalId] = useState(''); const [notice, setNotice] = useState('')
  const connections = useQuery({ queryKey: ['connections', 'attribute-mapping'], queryFn: () => hubApi<Page<Connection>>('/connections?limit=200') })
  const categories = useQuery({ queryKey: ['categories', 'attribute-mapping'], queryFn: () => hubApi<Page<LocalCategory>>('/catalog/categories?limit=200') })
  const localAttributes = useQuery({ queryKey: ['attributes', 'mapping'], queryFn: () => hubApi<Page<LocalAttribute>>('/catalog/attributes?limit=200') })
  const categoryMapping = useQuery({ queryKey: ['category-mapping', categoryId, connectionId], queryFn: () => hubApi<CatalogMapping | null>(`/mappings/categories/${categoryId}?connectionId=${encodeURIComponent(connectionId)}`), enabled: !!categoryId && !!connectionId, retry: false })
  const categoryScope = categoryMapping.data?.externalId ?? ''
  const references = useQuery({ queryKey: ['reference-attributes', connectionId, categoryScope], queryFn: () => hubApi<ReferenceData>(`/reference-data/categories/${encodeURIComponent(categoryScope)}/attributes?connectionId=${encodeURIComponent(connectionId)}`), enabled: !!connectionId && !!categoryScope, retry: false })
  const mapping = useQuery({ queryKey: ['attribute-mapping', localId, connectionId, categoryScope], queryFn: () => hubApi<CatalogMapping | null>(`/mappings/attributes/${localId}?connectionId=${encodeURIComponent(connectionId)}&scopeExternalId=${encodeURIComponent(categoryScope)}`), enabled: !!localId && !!connectionId && !!categoryScope, retry: false })
  const sync = useMutation({ mutationFn: () => hubApi(`/connections/${connectionId}/reference-sync-jobs?resourceType=CATEGORY_ATTRIBUTES&parentExternalId=${encodeURIComponent(categoryScope)}`, { method: 'POST', headers: { 'Idempotency-Key': idempotency() }, body: '{}' }), onSuccess: () => setNotice('Kategori özellikleri salt-okunur eşitleme kuyruğuna alındı.'), onError: reason => setNotice(reason instanceof Error ? reason.message : 'Özellik eşitleme başlatılamadı.') })
  const save = useMutation({ mutationFn: () => {
    if (!references.data || !localId || !externalId) throw new Error('Bağlantı, kategori, panel özelliği ve Trendyol özelliği zorunludur.')
    return hubApi<CatalogMapping>(`/mappings/attributes/${localId}`, { method: 'PUT', headers: mapping.data ? { 'If-Match': `"v${mapping.data.version}"` } : {}, body: JSON.stringify({ connectionId, snapshotId: references.data.snapshotId, externalId, status: 'VERIFIED' }) })
  }, onSuccess: async value => { setNotice('Özellik eşlemesi doğrulandı ve kategori kapsamında kaydedildi.'); setExternalId(value.externalId); await client.invalidateQueries({ queryKey: ['attribute-mapping', localId, connectionId, categoryScope] }) }, onError: reason => setNotice(reason instanceof Error ? reason.message : 'Özellik eşlemesi kaydedilemedi.') })
  useEffect(() => { setExternalId(mapping.data?.externalId ?? '') }, [mapping.data])
  const activeConnections = connections.data?.items.filter(item => item.platformCode === 'TRENDYOL' && item.status === 'ACTIVE') ?? []; const localLeaves = categories.data?.items.filter(item => item.isActive && item.isLeaf) ?? []; const activeAttributes = localAttributes.data?.items.filter(item => item.isActive) ?? []; const remoteAttributes = references.data?.items.filter(item => item.isActive) ?? []
  return <section className="content f3 mapping-page"><div className="page-heading"><div><p className="eyebrow">Eşleştirme ayarları</p><h1>Özellik eşlemeleri</h1><p className="lede">Yerel özellikleri güncel Trendyol V2 kategori özelliği snapshot’ına kategori kapsamında eşleyin.</p></div><Badge value="SAFE READ" /></div>{notice && <div role="status" className="notice">{notice}</div>}
    <div className="button-row"><Link className="button-link secondary" to="/mappings/categories">Kategoriler</Link><Link className="button-link secondary" to="/mappings/categories?view=brands">Markalar</Link><Link className="button-link" to="/mappings/attributes">Özellikler</Link></div>
    <article className="panel mapping-step"><div className="editor-section-title"><span>1</span><div><h2>Kategori kapsamını seçin</h2><p>Özellik kimlikleri seçili ve doğrulanmış Trendyol yaprak kategorisi kapsamında tutulur.</p></div></div><div className="mapping-fields"><label>Özellik için aktif Trendyol bağlantısı<select aria-label="Özellik için aktif Trendyol bağlantısı" value={connectionId} onChange={event => { setConnectionId(event.target.value); setCategoryId(''); setLocalId(''); setExternalId(''); setNotice('') }}><option value="">Bağlantı seçin</option>{activeConnections.map(item => <option value={item.id} key={item.id}>{item.displayName} · {item.externalStoreId}</option>)}</select></label><label>Panel yaprak kategorisi<select aria-label="Özellik kapsamı panel kategorisi" value={categoryId} onChange={event => { setCategoryId(event.target.value); setLocalId(''); setExternalId(''); setNotice('') }} disabled={!connectionId}><option value="">Kategori seçin</option>{localLeaves.map(item => <option value={item.id} key={item.id}>{item.path}</option>)}</select></label></div>
      {categoryId && !categoryMapping.isLoading && !categoryMapping.data ? <div className="unknown"><strong>Kategori eşlemesi gerekli</strong><p>Özellikleri almadan önce panel kategorisini Trendyol yaprak kategorisiyle eşleyin.</p><Link className="button-link" to="/mappings/categories">Kategori eşlemelerine git</Link></div> : categoryScope && references.isError ? <div className="unknown"><strong>Güncel özellik snapshot’ı yok</strong><p>Seçili kategori için yalnız salt-okunur özellik listesini eşitleyin.</p><button disabled={sync.isPending} onClick={() => sync.mutate()}>{sync.isPending ? 'Kuyruğa alınıyor…' : 'Kategori özelliklerini eşitle'}</button></div> : null}</article>
    {references.data && <article className="panel mapping-step"><div className="editor-section-title"><span>2</span><div><h2>Özelliği eşleyin</h2><p>Bu işlem yalnız yerel mapping kaydı oluşturur; Trendyol’a yazmaz.</p></div></div><div className="mapping-fields"><label>Panel özelliği<select aria-label="Panel özelliği" value={localId} onChange={event => { setLocalId(event.target.value); setExternalId(''); setNotice('') }}><option value="">Özellik seçin</option>{activeAttributes.map(item => <option value={item.id} key={item.id}>{item.name} · {item.dataType}</option>)}</select></label><label>Trendyol kategori özelliği<select aria-label="Trendyol kategori özelliği" value={externalId} onChange={event => setExternalId(event.target.value)} disabled={!localId}><option value="">Özellik seçin</option>{remoteAttributes.map(item => <option value={item.externalId} key={item.externalId}>{item.name}{item.isRequired ? ' · zorunlu' : ''}{item.allowsCustomValue ? ' · serbest değer' : ''}</option>)}</select></label></div><div className="mapping-action"><span>{remoteAttributes.length.toLocaleString('tr-TR')} özellik · kategori {categoryScope}{mapping.data ? ` · mevcut eşleme v${mapping.data.version}` : ''}</span><button disabled={!localId || !externalId || save.isPending || mapping.isLoading} onClick={() => save.mutate()}>{save.isPending ? 'Kaydediliyor…' : mapping.data ? 'Eşlemeyi güncelle' : 'Eşlemeyi doğrula ve kaydet'}</button></div>{mapping.data && localId && <AttributeValueMappingEditor connectionId={connectionId} categoryScope={categoryScope} attribute={activeAttributes.find(item => item.id === localId)!} externalAttributeId={mapping.data.externalId} />}</article>}
  </section>
}

function AttributeValueMappingEditor({ connectionId, categoryScope, attribute, externalAttributeId }: { connectionId: string; categoryScope: string; attribute: LocalAttribute; externalAttributeId: string }) {
  const client = useQueryClient(); const [localValueId, setLocalValueId] = useState(''); const [externalValueId, setExternalValueId] = useState(''); const [notice, setNotice] = useState(''); const valueScope = `${categoryScope}/${externalAttributeId}`
  const references = useQuery({ queryKey: ['reference-attribute-values', connectionId, valueScope], queryFn: () => hubApi<ReferenceData>(`/reference-data/categories/${encodeURIComponent(categoryScope)}/attributes/${encodeURIComponent(externalAttributeId)}/values?connectionId=${encodeURIComponent(connectionId)}`), retry: false })
  const mapping = useQuery({ queryKey: ['attribute-value-mapping', localValueId, connectionId, valueScope], queryFn: () => hubApi<CatalogMapping | null>(`/mappings/attribute-values/${localValueId}?connectionId=${encodeURIComponent(connectionId)}&scopeExternalId=${encodeURIComponent(valueScope)}`), enabled: !!localValueId, retry: false })
  const sync = useMutation({ mutationFn: () => hubApi(`/connections/${connectionId}/reference-sync-jobs?resourceType=ATTRIBUTE_VALUES&parentExternalId=${encodeURIComponent(valueScope)}`, { method: 'POST', headers: { 'Idempotency-Key': idempotency() }, body: '{}' }), onSuccess: () => setNotice('Özellik değerleri salt-okunur eşitleme kuyruğuna alındı.'), onError: reason => setNotice(reason instanceof Error ? reason.message : 'Değer eşitleme başlatılamadı.') })
  const save = useMutation({ mutationFn: () => {
    if (!references.data || !localValueId || !externalValueId) throw new Error('Panel ve Trendyol özellik değeri zorunludur.')
    return hubApi<CatalogMapping>(`/mappings/attribute-values/${localValueId}`, { method: 'PUT', headers: mapping.data ? { 'If-Match': `"v${mapping.data.version}"` } : {}, body: JSON.stringify({ connectionId, snapshotId: references.data.snapshotId, externalId: externalValueId, status: 'VERIFIED' }) })
  }, onSuccess: async value => { setNotice('Özellik değeri eşlemesi doğrulandı.'); setExternalValueId(value.externalId); await client.invalidateQueries({ queryKey: ['attribute-value-mapping', localValueId, connectionId, valueScope] }) }, onError: reason => setNotice(reason instanceof Error ? reason.message : 'Değer eşlemesi kaydedilemedi.') })
  useEffect(() => { setExternalValueId(mapping.data?.externalId ?? '') }, [mapping.data])
  const localValues = attribute.values?.filter(item => item.isActive) ?? []; const remoteValues = references.data?.items.filter(item => item.isActive) ?? []
  if (!localValues.length) return <div className="unknown"><strong>Serbest değer özelliği</strong><p>Bu yerel özellik seçim listesi taşımıyor; Trendyol özelliği serbest değer kabul etmiyorsa yayınlama kapısı işlemi reddeder.</p></div>
  if (references.isError) return <div className="unknown"><strong>Güncel özellik değerleri snapshot’ı yok</strong><p>Seçili kategori ve özellik için salt-okunur değer listesini eşitleyin.</p>{notice && <p role="status">{notice}</p>}<button disabled={sync.isPending} onClick={() => sync.mutate()}>{sync.isPending ? 'Kuyruğa alınıyor…' : 'Özellik değerlerini eşitle'}</button></div>
  if (references.isLoading) return <Busy text="Özellik değerleri yükleniyor…" />
  return <div className="mapping-step nested"><h3>Özellik değeri eşlemesi</h3>{notice && <p role="status">{notice}</p>}<div className="mapping-fields"><label>Panel özellik değeri<select aria-label="Panel özellik değeri" value={localValueId} onChange={event => { setLocalValueId(event.target.value); setExternalValueId('') }}><option value="">Değer seçin</option>{localValues.map(item => <option value={item.id} key={item.id}>{item.value}</option>)}</select></label><label>Trendyol özellik değeri<select aria-label="Trendyol özellik değeri" value={externalValueId} onChange={event => setExternalValueId(event.target.value)} disabled={!localValueId}><option value="">Değer seçin</option>{remoteValues.map(item => <option value={item.externalId} key={item.externalId}>{item.name}</option>)}</select></label></div><div className="mapping-action"><span>{remoteValues.length.toLocaleString('tr-TR')} değer · kapsam {valueScope}</span><button disabled={!localValueId || !externalValueId || save.isPending || mapping.isLoading} onClick={() => save.mutate()}>{save.isPending ? 'Kaydediliyor…' : mapping.data ? 'Değer eşlemesini güncelle' : 'Değer eşlemesini kaydet'}</button></div></div>
}

export function BrandMappingPage() {
  const client = useQueryClient(); const [connectionId, setConnectionId] = useState(''); const [localId, setLocalId] = useState(''); const [externalId, setExternalId] = useState(''); const [notice, setNotice] = useState('')
  const connections = useQuery({ queryKey: ['connections', 'brand-mapping'], queryFn: () => hubApi<Page<Connection>>('/connections?limit=200') })
  const localBrands = useQuery({ queryKey: ['brands', 'mapping'], queryFn: () => hubApi<Page<LocalBrand>>('/catalog/brands?limit=200') })
  const references = useQuery({ queryKey: ['reference-brands', connectionId], queryFn: () => hubApi<ReferenceData>(`/reference-data/brands?connectionId=${encodeURIComponent(connectionId)}`), enabled: !!connectionId, retry: false })
  const mapping = useQuery({ queryKey: ['brand-mapping', localId, connectionId], queryFn: () => hubApi<CatalogMapping | null>(`/mappings/brands/${localId}?connectionId=${encodeURIComponent(connectionId)}`), enabled: !!localId && !!connectionId, retry: false })
  const save = useMutation({ mutationFn: () => {
    if (!references.data || !localId || !externalId) throw new Error('Bağlantı, panel markası ve Trendyol markası zorunludur.')
    return hubApi<CatalogMapping>(`/mappings/brands/${localId}`, { method: 'PUT', headers: mapping.data ? { 'If-Match': `"v${mapping.data.version}"` } : {}, body: JSON.stringify({ connectionId, snapshotId: references.data.snapshotId, externalId, status: 'VERIFIED' }) })
  }, onSuccess: async value => { setNotice('Marka eşlemesi doğrulandı ve kaydedildi.'); setExternalId(value.externalId); await client.invalidateQueries({ queryKey: ['brand-mapping', localId, connectionId] }) }, onError: reason => setNotice(reason instanceof Error ? reason.message : 'Eşleme kaydedilemedi.') })
  useEffect(() => { setExternalId(mapping.data?.externalId ?? '') }, [mapping.data])
  const trendyolConnections = connections.data?.items.filter(item => item.platformCode === 'TRENDYOL' && item.status === 'ACTIVE') ?? []
  const activeLocalBrands = localBrands.data?.items.filter(item => item.isActive) ?? []
  const externalBrands = references.data?.items.filter(item => item.isActive) ?? []

  return <section className="content f3 mapping-page"><div className="page-heading"><div><p className="eyebrow">Eşleştirme ayarları</p><h1>Marka eşlemeleri</h1><p className="lede">Yerel markayı doğrulanmış Trendyol marka snapshot’ındaki kimlikle eşleştirin.</p></div><Badge value="SAFE READ" /></div>{notice && <div role="status" className="notice">{notice}</div>}
    <div className="button-row"><Link className="button-link secondary" to="/mappings/categories">Kategoriler</Link><Link className="button-link" to="/mappings/categories?view=brands">Markalar</Link><Link className="button-link secondary" to="/mappings/attributes">Özellikler</Link></div>
    <article className="panel mapping-step"><div className="editor-section-title"><span>1</span><div><h2>Trendyol marka eşlemesi</h2><p>Bu işlem yalnız yerel mapping kaydı oluşturur; Trendyol’a veri göndermez.</p></div></div>
      <div className="mapping-fields"><label>Aktif Trendyol bağlantısı<select aria-label="Marka için aktif Trendyol bağlantısı" value={connectionId} onChange={event => { setConnectionId(event.target.value); setLocalId(''); setExternalId(''); setNotice('') }}><option value="">Bağlantı seçin</option>{trendyolConnections.map(item => <option value={item.id} key={item.id}>{item.displayName} · {item.externalStoreId}</option>)}</select></label>
        <label>Panel markası<select aria-label="Panel markası" value={localId} onChange={event => { setLocalId(event.target.value); setExternalId(''); setNotice('') }} disabled={!connectionId}><option value="">Marka seçin</option>{activeLocalBrands.map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label>
        <label>Trendyol markası<select aria-label="Trendyol markası" value={externalId} onChange={event => setExternalId(event.target.value)} disabled={!localId || references.isLoading || references.isError}><option value="">Marka seçin</option>{externalBrands.map(item => <option value={item.externalId} key={item.externalId}>{item.name}</option>)}</select></label></div>
      {connections.isError || localBrands.isError ? <ErrorBox error={connections.error ?? localBrands.error} /> : references.isError ? <div className="unknown"><strong>Güncel marka snapshot’ı yok</strong><p>Bağlantı ekranından “Markaları eşitle” işlemini çalıştırın.</p><Link className="button-link" to={`/integrations/${connectionId}`}>Bağlantıya git</Link></div> : references.isLoading ? <Busy text="Marka snapshot’ı yükleniyor…" /> : connectionId && references.data ? <div className="mapping-action"><span>{externalBrands.length.toLocaleString('tr-TR')} marka · snapshot {new Date(references.data.fetchedAt).toLocaleString('tr-TR')}{mapping.data ? ` · mevcut eşleme v${mapping.data.version}` : ''}</span><button type="button" disabled={!localId || !externalId || save.isPending || mapping.isLoading} onClick={() => save.mutate()}>{save.isPending ? 'Kaydediliyor…' : mapping.data ? 'Eşlemeyi güncelle' : 'Eşlemeyi doğrula ve kaydet'}</button></div> : null}
    </article></section>
}

function ListPage({ eyebrow, title, description, children }: { eyebrow: string; title: string; description: string; children: React.ReactNode }) { return <section className="content f3"><div className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="lede">{description}</p></div><Badge value="LIVE READ" /></div><div className="panel">{children}</div></section> }
