import { useState, type FormEvent } from 'react'
import { Link, useParams } from 'react-router'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { hubApi } from './api'

type Page<T> = { items: T[]; nextCursor: string | null; hasMore: boolean }
type Invoice = { id: string; orderNumber: string; invoiceType: string; status: string; currency: string; payableTotal: number; invoiceNumber: string | null; dueAt: string | null; createdAt: string; version: number }
type InvoiceDetail = Invoice & { orderId: string; packageId: string | null; providerConnectionId: string; sequencePurpose: string; taxExclusiveTotal: number; discountTotal: number; taxTotal: number; issuedAt: string | null; lastErrorCode: string | null; lines: Array<{ id: string; lineSequence: number; description: string; sku: string | null; unit: string; quantity: number; unitPrice: number; vatRate: number; lineTotal: number }>; documents: Array<{ id: string; documentType: string; sha256: string; createdAt: string }>; attempts: Array<{ attemptNumber: number; outcome: string; errorCode: string | null }>; deliveries: Array<{ id: string; deliveryType: string; status: string; errorCode: string | null }>; allowedActions: string[] }
type Connection = { id: string; platformCode: string; displayName: string; status: string }
type LegalEntity = { id: string; title: string; maskedTaxId: string; status: string; version: number }
type Policy = { id: string; providerConnectionId: string; triggerState: string; packageScope: string; dueRule: string; roundingRule: string; adjustmentRule: string; autoSubmit: boolean; version: number }

function ErrorBox({ error }: { error: unknown }) { return <div role="alert" className="error">{error instanceof Error ? error.message : 'İşlem tamamlanamadı.'}</div> }
function Busy() { return <div className="status inline" role="status"><div className="spinner" /><strong>Veriler yükleniyor…</strong></div> }
function Badge({ value }: { value: string }) { const tone = ['READY', 'ACCEPTED', 'COMPLETED', 'ACTIVE'].includes(value) ? 'good' : ['UNKNOWN_RESULT', 'VALIDATION_FAILED', 'MANUAL_REVIEW', 'UNAPPROVED', 'UNKNOWN'].includes(value) ? 'warn' : 'neutral'; return <span className={`badge ${tone}`}>{value}</span> }

export function InvoicesPage() {
  const query = useQuery({ queryKey: ['invoices'], queryFn: () => hubApi<Page<Invoice>>('/invoices') })
  return <section className="content f3"><div className="page-heading"><div><p className="eyebrow">Mali belgeler</p><h1>Faturalar</h1><p className="lede">Fatura tipi ve dış işlemler yalnız doğrulanmış capability ile açılır. UNKNOWN durumunda sistem güvenli biçimde kapalı kalır.</p></div><Badge value="F4" /></div><div className="panel">{query.isLoading ? <Busy /> : query.isError ? <ErrorBox error={query.error} /> : !query.data?.items.length ? <div className="empty"><strong>Fatura yok</strong><p>Sipariş, legal entity ve onaylı fatura politikası hazır olduğunda taslak oluşturabilirsiniz.</p></div> : <div className="data-table" role="table">{query.data.items.map(item => <Link role="row" to={`/invoices/${item.id}`} key={item.id}><span><strong>{item.orderNumber}</strong><small>{item.invoiceNumber ?? 'Taslak'}</small></span><Badge value={item.status} /><span>{item.invoiceType}</span><span>{item.payableTotal.toLocaleString('tr-TR', { style: 'currency', currency: item.currency })}</span></Link>)}</div>}</div></section>
}

export function InvoiceDetailPage() {
  const { id = '' } = useParams(); const client = useQueryClient(); const [notice, setNotice] = useState('')
  const query = useQuery({ queryKey: ['invoice', id], queryFn: () => hubApi<InvoiceDetail>(`/invoices/${id}`) })
  const validate = useMutation({ mutationFn: (version: number) => hubApi<InvoiceDetail>(`/invoices/${id}/validate`, { method: 'POST', headers: { 'If-Match': `"v${version}"` } }), onSuccess: () => { setNotice('Yerel doğrulama tamamlandı.'); void client.invalidateQueries({ queryKey: ['invoice', id] }) }, onError: error => setNotice(error instanceof Error ? error.message : 'Doğrulama başarısız.') })
  if (query.isLoading) return <section className="content"><Busy /></section>; if (query.isError || !query.data) return <section className="content"><ErrorBox error={query.error} /></section>; const invoice = query.data
  return <section className="content f3"><Link className="back" to="/invoices">← Faturalar</Link><div className="page-heading"><div><p className="eyebrow">Fatura detayı</p><h1>{invoice.orderNumber}</h1><p className="lede">{invoice.invoiceNumber ?? 'Henüz numara atanmadı'} · {invoice.invoiceType}</p></div><Badge value={invoice.status} /></div>{notice && <div role="status" className="notice">{notice}</div>}<div className="grid"><article><small>Ödenecek</small><strong>{invoice.payableTotal.toLocaleString('tr-TR', { style: 'currency', currency: invoice.currency })}</strong><p>Vergi: {invoice.taxTotal.toLocaleString('tr-TR')}</p></article><article><small>Provider</small><strong>{invoice.providerConnectionId}</strong><p>Capability kapıları sunucuda uygulanır.</p></article><article><small>Son hata</small><strong>{invoice.lastErrorCode ?? 'Yok'}</strong><p>UNKNOWN sonuç otomatik başarı sayılmaz.</p></article></div><div className="panel"><h2>Satırlar</h2><div className="data-table compact" role="table">{invoice.lines.map(line => <div role="row" key={line.id}><span><strong>{line.description}</strong><small>{line.sku ?? 'SKU yok'}</small></span><span>{line.quantity} {line.unit}</span><span>%{line.vatRate}</span><span>{line.lineTotal.toLocaleString('tr-TR', { style: 'currency', currency: invoice.currency })}</span></div>)}</div></div><div className="panel"><h2>Kullanılabilir işlemler</h2>{invoice.allowedActions.length ? <div className="button-row">{invoice.allowedActions.map(action => action === 'VALIDATE' ? <button key={action} onClick={() => validate.mutate(invoice.version)} disabled={validate.isPending}>Yerel doğrula</button> : <button key={action} disabled title="Parola ile yeniden doğrulama gerektirir">{action}</button>)}</div> : <div className="unknown"><strong>Dış işlemler kapalı</strong><p>Capability, mali politika ve yazma anahtarları birlikte doğrulanmadan submit, delivery veya iptal sunulmaz.</p></div>}</div></section>
}

export function BillingSettingsPage() {
  const client = useQueryClient(); const [connectionId, setConnectionId] = useState(''); const [message, setMessage] = useState('')
  const connections = useQuery({ queryKey: ['connections'], queryFn: () => hubApi<Page<Connection>>('/connections') })
  const legal = useQuery({ queryKey: ['legal-entity'], queryFn: () => hubApi<LegalEntity>('/billing/legal-entity-profile'), retry: false })
  const policy = useQuery({ queryKey: ['invoice-policy', connectionId], queryFn: () => hubApi<Policy>(`/billing/invoice-policies/${connectionId}`), enabled: !!connectionId, retry: false })
  async function saveLegal(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); try { await hubApi('/billing/legal-entity-profile', { method: 'PUT', headers: legal.data ? { 'If-Match': `"v${legal.data.version}"` } : {}, body: JSON.stringify({ title: data.get('title'), taxId: data.get('taxId'), addressSnapshotJson: data.get('address'), contactSnapshotJson: data.get('contact'), status: 'ACTIVE' }) }); setMessage('Legal entity güvenli olarak kaydedildi.'); await client.invalidateQueries({ queryKey: ['legal-entity'] }) } catch (error) { setMessage(error instanceof Error ? error.message : 'Kayıt başarısız.') } }
  async function savePolicy(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!connectionId) return; const data = new FormData(event.currentTarget); try { await hubApi(`/billing/invoice-policies/${connectionId}`, { method: 'PUT', headers: policy.data ? { 'If-Match': `"v${policy.data.version}"` } : {}, body: JSON.stringify({ triggerState: data.get('triggerState'), packageScope: data.get('packageScope'), dueRule: data.get('dueRule'), roundingRule: data.get('roundingRule'), adjustmentRule: data.get('adjustmentRule'), autoSubmit: false }) }); setMessage('Politika kaydedildi; otomatik submit kapalı kaldı.'); await client.invalidateQueries({ queryKey: ['invoice-policy', connectionId] }) } catch (error) { setMessage(error instanceof Error ? error.message : 'Kayıt başarısız.') } }
  const providers = connections.data?.items.filter(x => x.platformCode === 'TRENDYOL_EFATURAM') ?? []
  return <section className="content f3"><div className="page-heading"><div><p className="eyebrow">Faturalama ayarları</p><h1>Mali profil ve politika</h1><p className="lede">VKN/TCKN biçim kontrolü mükellefiyet kanıtı değildir. Onaysız politika değerleri fail-closed çalışır.</p></div><Badge value="AUTO SUBMIT OFF" /></div>{message && <div role="status" className="notice">{message}</div>}<div className="split"><form className="panel form-panel" onSubmit={saveLegal}><h2>Legal entity</h2><label>Unvan<input name="title" defaultValue={legal.data?.title ?? ''} required /></label><label>VKN/TCKN<input name="taxId" inputMode="numeric" pattern="[0-9]{10,11}" required /></label><label>Adres snapshot JSON<textarea name="address" defaultValue="{}" required /></label><label>İletişim snapshot JSON<textarea name="contact" defaultValue="{}" required /></label><button>Şifreli kaydet</button>{legal.data && <p>Mevcut: {legal.data.title} · {legal.data.maskedTaxId}</p>}</form><form className="panel form-panel" onSubmit={savePolicy}><h2>Fatura politikası</h2><label>Provider<select value={connectionId} onChange={event => setConnectionId(event.target.value)} required><option value="">Seçin</option>{providers.map(item => <option key={item.id} value={item.id}>{item.displayName}</option>)}</select></label><label>Tetikleme durumu<input name="triggerState" defaultValue={policy.data?.triggerState ?? 'UNAPPROVED'} required /></label><label>Paket kapsamı<input name="packageScope" defaultValue={policy.data?.packageScope ?? 'UNAPPROVED'} required /></label><label>Vade kuralı<input name="dueRule" defaultValue={policy.data?.dueRule ?? 'UNAPPROVED'} required /></label><label>Yuvarlama kuralı<input name="roundingRule" defaultValue={policy.data?.roundingRule ?? 'UNAPPROVED'} required /></label><label>Düzeltme kuralı<input name="adjustmentRule" defaultValue={policy.data?.adjustmentRule ?? 'UNAPPROVED'} required /></label><button disabled={!connectionId}>Politikayı kaydet</button><p>Otomatik submit bu ekrandan açılamaz.</p></form></div></section>
}
