import { useState, type FormEvent } from 'react'
import { Link, useParams } from 'react-router'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { hubApi } from './api'

type Page<T> = { items: T[]; nextCursor: string | null; hasMore: boolean }
type Invoice = { id: string; orderNumber: string; invoiceType: string; status: string; currency: string; payableTotal: number; invoiceNumber: string | null; dueAt: string | null; createdAt: string; version: number }
type InvoiceDetail = Invoice & { orderId: string; packageId: string | null; providerConnectionId: string; sequencePurpose: string; ettnUuid: string | null; taxExclusiveTotal: number; discountTotal: number; taxTotal: number; note: string; issuedAt: string | null; lastErrorCode: string | null; lines: Array<{ id: string; lineSequence: number; description: string; sku: string | null; unit: string; quantity: number; unitPrice: number; discountAmount: number; vatRate: number; vatAmount: number; lineTotal: number }>; documents: Array<{ id: string; documentType: string; sha256: string; createdAt: string }>; attempts: Array<{ attemptNumber: number; outcome: string; errorCode: string | null; startedAt: string; completedAt: string | null }>; deliveries: Array<{ id: string; deliveryType: string; status: string; externalReference: string | null; errorCode: string | null; createdAt: string }>; allowedActions: string[] }
type Connection = { id: string; platformCode: string; displayName: string; status: string }
type LegalEntity = { id: string; title: string; maskedTaxId: string; status: string; version: number }
type Policy = { id: string; providerConnectionId: string; triggerState: string; packageScope: string; dueRule: string; roundingRule: string; adjustmentRule: string; autoSubmit: boolean; version: number }
type Taxpayer = { taxId: string; isRegistered: boolean; providerCustomerId: string | null; checkedAt: string; applications: Array<{ type: number; serviceName: string; gibStatus: string; activated: boolean; activationDate: string | null; deactivationDate: string | null }> }

function idempotency() { return crypto.randomUUID() }
function ErrorBox({ error }: { error: unknown }) { return <div role="alert" className="error">{error instanceof Error ? error.message : 'İşlem tamamlanamadı.'}</div> }
function Busy() { return <div className="status inline" role="status"><div className="spinner" /><strong>Veriler yükleniyor…</strong></div> }
function Badge({ value }: { value: string }) { const tone = ['READY', 'ACCEPTED', 'COMPLETED', 'ACTIVE', 'SUPPORTED', 'CANCELLED'].includes(value) ? 'good' : ['UNKNOWN_RESULT', 'VALIDATION_FAILED', 'MANUAL_REVIEW', 'UNAPPROVED', 'UNKNOWN', 'CANCELLATION_PENDING'].includes(value) ? 'warn' : 'neutral'; return <span className={`badge ${tone}`}>{value}</span> }
function actionLabel(action: string) { return ({ SUBMIT: 'E-Faturam’a gönder', RECONCILE: 'Durumu uzlaştır', DELIVER: 'Trendyol’a fatura linkini ilet', CANCEL: 'E-Arşiv iptal isteği', VALIDATE: 'Yerel doğrula' } as Record<string, string>)[action] ?? action }

export function InvoicesPage() {
  const [search, setSearch] = useState(''); const [tab, setTab] = useState('ALL'); const [invoiceType, setInvoiceType] = useState('ALL'); const [from, setFrom] = useState(''); const [to, setTo] = useState('')
  const query = useQuery({ queryKey: ['invoices'], queryFn: () => hubApi<Page<Invoice>>('/invoices?limit=200') })
  const items = query.data?.items ?? []; const normalized = search.trim().toLocaleLowerCase('tr-TR')
  const visible = items.filter(item => {
    const tabMatch = tab === 'ALL' || (tab === 'DUE' && !['COMPLETED', 'CANCELLED', 'CANCELLED_LOCAL'].includes(item.status)) || (tab === 'COMPLETED' && item.status === 'COMPLETED') || (tab === 'ERROR' && ['VALIDATION_FAILED', 'MANUAL_REVIEW', 'REJECTED', 'CANCELLATION_REJECTED'].includes(item.status))
    const typeMatch = invoiceType === 'ALL' || item.invoiceType === invoiceType
    const created = new Date(item.createdAt); const dateMatch = (!from || created >= new Date(`${from}T00:00:00`)) && (!to || created <= new Date(`${to}T23:59:59.999`))
    return tabMatch && typeMatch && dateMatch && (!normalized || [item.orderNumber, item.invoiceNumber ?? ''].some(value => value.toLocaleLowerCase('tr-TR').includes(normalized)))
  })
  const tabs = [['ALL', 'Tümü'], ['DUE', 'Kesilecekler'], ['COMPLETED', 'Kesilenler'], ['ERROR', 'Hatalı']] as const
  return <section className="content f3 invoices-page">
    <div className="page-heading"><div><p className="eyebrow">Mali belgeler</p><h1>Trendyol E-Faturam</h1><p className="lede">E-Fatura ve internet satışı E-Arşiv belgelerini kontrollü durum makineleriyle yönetin.</p></div><Badge value="FAIL-CLOSED" /></div>
    <div className="invoice-metrics metrics"><article><small>Tamamlanan</small><strong>{items.filter(item => item.status === 'COMPLETED').length}</strong><span>Trendyol’a teslim edilen</span></article><article><small>Provider kabulü</small><strong>{items.filter(item => item.status === 'ACCEPTED').length}</strong><span>belgesi alınabilir</span></article><article><small>İnceleme</small><strong>{items.filter(item => ['VALIDATION_FAILED', 'MANUAL_REVIEW', 'REJECTED'].includes(item.status)).length}</strong><span>operatör müdahalesi</span></article></div>
    <div className="invoice-toolbar"><label className="order-search"><span aria-hidden="true">⌕</span><input aria-label="Fatura ara" placeholder="Sipariş veya fatura no ara..." value={search} onChange={event => setSearch(event.target.value)} /></label><label>Fatura tipi<select value={invoiceType} onChange={event => setInvoiceType(event.target.value)}><option value="ALL">Tümü</option><option value="EARSIVFATURA">E-Arşiv</option><option value="TEMELFATURA">Temel E-Fatura</option><option value="TICARIFATURA">Ticari E-Fatura</option></select></label><label>Başlangıç<input type="date" value={from} onChange={event => setFrom(event.target.value)} /></label><label>Bitiş<input type="date" value={to} onChange={event => setTo(event.target.value)} /></label></div>
    <div className="invoice-tabs" role="tablist">{tabs.map(([value, label]) => <button key={value} type="button" role="tab" aria-selected={tab === value} className={tab === value ? 'active' : ''} onClick={() => setTab(value)}>{label}</button>)}</div>
    <div className="panel invoice-workspace">{query.isLoading ? <Busy /> : query.isError ? <ErrorBox error={query.error} /> : !visible.length ? <div className="empty"><strong>Fatura yok</strong><p>{items.length ? 'Seçili filtreyle eşleşen fatura bulunamadı.' : 'Sipariş detayından paket bazlı fatura taslağı oluşturun.'}</p></div> : <div className="data-table invoice-table" role="table"><div className="table-head" role="row"><span>Sipariş / Fatura</span><span>Durum</span><span>Tür</span><span>Tutar</span></div>{visible.map(item => <Link role="row" to={`/invoices/${item.id}`} key={item.id}><span><strong>{item.orderNumber}</strong><small>{item.invoiceNumber ?? 'Taslak'}</small></span><Badge value={item.status} /><span>{item.invoiceType}</span><span>{item.payableTotal.toLocaleString('tr-TR', { style: 'currency', currency: item.currency })}</span></Link>)}</div>}</div>
  </section>
}

export function InvoiceDetailPage() {
  const { id = '' } = useParams(); const client = useQueryClient(); const [notice, setNotice] = useState(''); const [password, setPassword] = useState(''); const [confirmed, setConfirmed] = useState(false)
  const query = useQuery({ queryKey: ['invoice', id], queryFn: () => hubApi<InvoiceDetail>(`/invoices/${id}`) })
  const operation = useMutation({
    mutationFn: async ({ action, invoice }: { action: string; invoice: InvoiceDetail }) => {
      if (action === 'VALIDATE') return hubApi<InvoiceDetail>(`/invoices/${id}/validate`, { method: 'POST', headers: { 'If-Match': `"v${invoice.version}"` } })
      if (action === 'RECONCILE') return hubApi(`/invoices/${id}/reconcile-jobs`, { method: 'POST', headers: { 'Idempotency-Key': idempotency() } })
      const endpoint = action === 'SUBMIT' ? 'submit-jobs' : action === 'DELIVER' ? 'marketplace-delivery-jobs' : 'cancellation-jobs'
      return hubApi(`/invoices/${id}/${endpoint}`, { method: 'POST', headers: { 'Idempotency-Key': idempotency(), ...(action !== 'DELIVER' ? { 'If-Match': `"v${invoice.version}"` } : {}) }, body: JSON.stringify({ password, confirmed }) })
    },
    onSuccess: (_value, variables) => { setNotice(variables.action === 'VALIDATE' ? 'Yerel doğrulama tamamlandı.' : 'İş güvenli kuyruğa alındı.'); setPassword(''); setConfirmed(false); void client.invalidateQueries({ queryKey: ['invoice', id] }) },
    onError: error => setNotice(error instanceof Error ? error.message : 'İşlem başarısız.')
  })
  if (query.isLoading) return <section className="content"><Busy /></section>; if (query.isError || !query.data) return <section className="content"><ErrorBox error={query.error} /></section>; const invoice = query.data
  const protectedActions = invoice.allowedActions.filter(action => action !== 'VALIDATE' && action !== 'RECONCILE')
  return <section className="content f3"><Link className="back" to="/invoices">← Faturalar</Link><div className="page-heading"><div><p className="eyebrow">Fatura detayı</p><h1>{invoice.orderNumber}</h1><p className="lede">{invoice.invoiceNumber ?? 'Henüz numara atanmadı'} · {invoice.invoiceType}</p></div><Badge value={invoice.status} /></div>
    {notice && <div role="status" className="notice">{notice}</div>}
    <div className="grid"><article><small>Ödenecek</small><strong>{invoice.payableTotal.toLocaleString('tr-TR', { style: 'currency', currency: invoice.currency })}</strong><p>Vergi: {invoice.taxTotal.toLocaleString('tr-TR')}</p></article><article><small>ETTN / UUID</small><strong>{invoice.ettnUuid ?? 'Henüz atanmadı'}</strong><p>{invoice.sequencePurpose} · {invoice.issuedAt ? new Date(invoice.issuedAt).toLocaleString('tr-TR') : 'Henüz düzenlenmedi'}</p></article><article><small>Son hata</small><strong>{invoice.lastErrorCode ?? 'Yok'}</strong><p>Bilinmeyen sonuç otomatik başarı sayılmaz.</p></article></div>
    <div className="panel"><h2>Satırlar</h2><div className="data-table compact" role="table">{invoice.lines.map(line => <div role="row" key={line.id}><span><strong>{line.description}</strong><small>{line.sku ?? 'SKU yok'} · indirim {line.discountAmount.toLocaleString('tr-TR')}</small></span><span>{line.quantity} {line.unit}</span><span>%{line.vatRate}</span><span>{line.lineTotal.toLocaleString('tr-TR', { style: 'currency', currency: invoice.currency })}</span></div>)}</div></div>
    <div className="split"><div className="panel"><h2>Provider denemeleri</h2>{invoice.attempts.length ? <div className="card-list">{invoice.attempts.map(item => <div className="record-card" key={item.attemptNumber}><span><strong>Deneme #{item.attemptNumber}</strong><small>{item.errorCode ?? 'Hata yok'}</small></span><Badge value={item.outcome} /></div>)}</div> : <p>Henüz dış gönderim denemesi yok.</p>}</div><div className="panel"><h2>Trendyol teslimleri</h2>{invoice.deliveries.length ? <div className="card-list">{invoice.deliveries.map(item => <div className="record-card" key={item.id}><span><strong>{item.deliveryType}</strong><small>{item.externalReference ?? item.errorCode ?? 'Referans bekleniyor'}</small></span><Badge value={item.status} /></div>)}</div> : <p>Henüz pazaryeri fatura linki teslimi yok.</p>}</div></div>
    <div className="panel"><h2>Belgeler</h2>{invoice.documents.length ? <div className="card-list">{invoice.documents.map(document => <a className="record-card" key={document.id} href={`/api/v1/invoices/${invoice.id}/documents/${document.id}/content`} target="_blank" rel="noreferrer"><span><strong>{document.documentType}</strong><small>SHA-256 {document.sha256.slice(0, 16)}…</small></span><span>Güvenli aç ↗</span></a>)}</div> : <p>Provider kabulünden sonra kalıcı PDF alınır; PDF oluşması tek başına mali kabul değildir.</p>}</div>
    {protectedActions.length > 0 && <form className="panel form-panel" onSubmit={event => event.preventDefault()}><h2>Dış mali işlem onayı</h2><p>Parola yalnız bu işlem için yeniden doğrulanır. Sunucu açık onay, capability, connection ve global yazma kapılarını ayrıca denetler.</p><label>Hesap parolası<input type="password" autoComplete="current-password" value={password} onChange={event => setPassword(event.target.value)} /></label><label className="check"><input type="checkbox" checked={confirmed} onChange={event => setConfirmed(event.target.checked)} /> Bu dış mali işlemi açıkça onaylıyorum.</label></form>}
    <div className="panel"><h2>Kullanılabilir işlemler</h2>{invoice.allowedActions.length ? <div className="button-row">{invoice.allowedActions.map(action => <button key={action} type="button" onClick={() => operation.mutate({ action, invoice })} disabled={operation.isPending || (protectedActions.includes(action) && (!password || !confirmed))}>{actionLabel(action)}</button>)}</div> : <div className="unknown"><strong>Dış işlemler kapalı</strong><p>Capability, mali politika, bağlantı ayarı ve yazma anahtarları birlikte doğrulanmadan işlem sunulmaz.</p></div>}</div>
  </section>
}

export function BillingSettingsPage() {
  const client = useQueryClient(); const [connectionId, setConnectionId] = useState(''); const [message, setMessage] = useState(''); const [taxpayer, setTaxpayer] = useState<Taxpayer | null>(null); const [taxpayerError, setTaxpayerError] = useState('')
  const connections = useQuery({ queryKey: ['connections'], queryFn: () => hubApi<Page<Connection>>('/connections') })
  const legal = useQuery({ queryKey: ['legal-entity'], queryFn: () => hubApi<LegalEntity>('/billing/legal-entity-profile'), retry: false })
  const policy = useQuery({ queryKey: ['invoice-policy', connectionId], queryFn: () => hubApi<Policy>(`/billing/invoice-policies/${connectionId}`), enabled: !!connectionId, retry: false })
  async function saveLegal(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const optional = (name: string) => data.get(name)?.toString().trim() || undefined; const addressSnapshotJson = JSON.stringify({ countryCode: 'TR', city: optional('city'), district: optional('district'), fullAddress: optional('address'), postalCode: optional('postalCode') }); const contactSnapshotJson = JSON.stringify({ email: optional('email'), phone: optional('phone') }); try { await hubApi('/billing/legal-entity-profile', { method: 'PUT', headers: legal.data ? { 'If-Match': `"v${legal.data.version}"` } : {}, body: JSON.stringify({ title: data.get('title'), taxId: data.get('taxId'), addressSnapshotJson, contactSnapshotJson, status: 'ACTIVE' }) }); setMessage('Şirket bilgileri şifreli olarak kaydedildi.'); await client.invalidateQueries({ queryKey: ['legal-entity'] }) } catch (error) { setMessage(error instanceof Error ? error.message : 'Kayıt başarısız.') } }
  async function savePolicy(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!connectionId) return; try { await hubApi(`/billing/invoice-policies/${connectionId}`, { method: 'PUT', headers: policy.data ? { 'If-Match': `"v${policy.data.version}"` } : {}, body: JSON.stringify({ triggerState: 'MANUAL_CONFIRMED', packageScope: 'SHIPMENT_PACKAGE', dueRule: 'IMMEDIATE', roundingRule: 'LINE_HALF_AWAY_FROM_ZERO', adjustmentRule: 'REJECT_OVER_ONE_KURUS', autoSubmit: false }) }); setMessage('Manuel paket faturası politikası kaydedildi; otomatik gönderim kapalı kaldı.'); await client.invalidateQueries({ queryKey: ['invoice-policy', connectionId] }) } catch (error) { setMessage(error instanceof Error ? error.message : 'Kayıt başarısız.') } }
  async function queryTaxpayer(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!connectionId) return; const data = new FormData(event.currentTarget); setTaxpayer(null); setTaxpayerError(''); try { setTaxpayer(await hubApi<Taxpayer>(`/billing/taxpayers/${encodeURIComponent(String(data.get('taxId')))}?connectionId=${connectionId}`)) } catch (error) { setTaxpayerError(error instanceof Error ? error.message : 'Mükellef sorgusu başarısız.') } }
  const providers = connections.data?.items.filter(x => x.platformCode === 'TRENDYOL_EFATURAM') ?? []
  return <section className="content f3"><div className="page-heading"><div><p className="eyebrow">Faturalama ayarları</p><h1>Mali profil, mükellefiyet ve politika</h1><p className="lede">Fatura tipi Trendyol siparişindeki e‑Fatura uygunluk snapshotı ve bağlantıda seçilen Temel/Ticari senaryo üzerinden belirlenir; provider sorgusu operatör doğrulamasıdır.</p></div><Badge value="AUTO SUBMIT OFF" /></div>{message && <div role="status" className="notice">{message}</div>}
    <div className="split"><form className="panel form-panel" onSubmit={saveLegal}><h2>Şirket bilgileri</h2><p>Bu bilgiler fatura taslağında kullanılır ve hassas alanlar şifreli saklanır.</p><label>Yasal unvan<input name="title" defaultValue={legal.data?.title ?? ''} required /></label><label>VKN/TCKN<input name="taxId" inputMode="numeric" pattern="[0-9]{10,11}" required /></label><label>Açık adres<textarea name="address" required /></label><label>İl<input name="city" required /></label><label>İlçe<input name="district" required /></label><label>Posta kodu<input name="postalCode" inputMode="numeric" /></label><label>E-posta<input name="email" type="email" /></label><label>Telefon<input name="phone" type="tel" /></label><button>Şifreli kaydet</button>{legal.data && <p>Mevcut: {legal.data.title} · {legal.data.maskedTaxId}</p>}</form>
      <div><form className="panel form-panel" onSubmit={savePolicy}><h2>Manuel paket faturası politikası</h2><label>Provider<select value={connectionId} onChange={event => { setConnectionId(event.target.value); setTaxpayer(null) }} required><option value="">Seçin</option>{providers.map(item => <option key={item.id} value={item.id}>{item.displayName}</option>)}</select></label><label>Tetikleme durumu<input value="MANUAL_CONFIRMED" readOnly /></label><label>Paket kapsamı<input value="SHIPMENT_PACKAGE" readOnly /></label><label>Yuvarlama kuralı<input value="LINE_HALF_AWAY_FROM_ZERO" readOnly /></label><label>Düzeltme kuralı<input value="REJECT_OVER_ONE_KURUS" readOnly /></label><button disabled={!connectionId}>Manuel paket politikasını kaydet</button><p>Gerçek gönderim ayrıca parola ve açık onay ister.</p></form>
        <form className="panel form-panel" onSubmit={queryTaxpayer}><h2>E-Fatura mükellefiyet sorgusu</h2><p>Yalnız MARKETPLACE modeli, sayısal Partner ID ve TAXPAYER_QUERY kanıtı ile çalışır.</p><label>VKN/TCKN<input name="taxId" inputMode="numeric" pattern="[0-9]{10,11}" required /></label><button disabled={!connectionId}>Provider’dan sorgula</button>{taxpayerError && <div role="alert" className="error">{taxpayerError}</div>}{taxpayer && <div className="unknown"><strong>{taxpayer.isRegistered ? 'Aktif e-belge başvurusu bulundu' : 'Aktif başvuru bulunamadı'}</strong><p>Kontrol: {new Date(taxpayer.checkedAt).toLocaleString('tr-TR')}</p>{taxpayer.applications.map((item, index) => <div className="record-card" key={`${item.type}-${index}`}><span><strong>{item.serviceName || `Servis ${item.type}`}</strong><small>{item.gibStatus || 'GİB durumu belirtilmedi'}</small></span><Badge value={item.activated ? 'ACTIVE' : 'INACTIVE'} /></div>)}</div>}</form></div>
    </div>
  </section>
}
